#!/usr/bin/env python3
"""build_colab_fireviewer_nb.py - generate the FireViewer v6 Colab notebook.

Prepares the dataset ON the Colab machine (the corpus is pulled from HuggingFace, so
nothing large is uploaded) and trains in a way that survives losing the editor:

  * the upload bundle is read from Google Drive (`colab_upload.zip`, ~83 MB);
  * EVERY stage writes a debug log to Drive (`<DRIVE>/logs/<stage>.log`);
  * all run artifacts land on Drive - `<DRIVE>/runs/<name>/` holds `train.log`,
    `results.csv`, `args.yaml` and `weights/{last,best}.pt`;
  * training is launched DETACHED (`subprocess.Popen(start_new_session=True)` via
    dev_scripts/colab_train_v6.py), so closing VS Code / the tab / the kernel cannot stop
    it; the live log stays local for speed and is mirrored to Drive every epoch.

Cells: deps -> config -> logging -> Drive+bundle -> HF download -> convert -> dedup ->
BALANCE -> verify -> negatives -> trainer check -> LAUNCH -> STATUS -> RESUME -> COLLECT.

Usage:
    python dev_scripts/build_colab_fireviewer_nb.py \
        --out model-training/datasets--fireviewer--fire-smoke-detection-corpus-v1/fireviewer-v6-bootstrap-colab.ipynb
"""
import argparse
import json
import os

DEFAULT_OUT = "notebooks/fireviewer-v6-bootstrap-colab.ipynb"


def md(source):
    return {"cell_type": "markdown", "metadata": {}, "source": source}


def code(source):
    return {"cell_type": "code", "execution_count": None, "metadata": {}, "outputs": [],
            "source": source}


C_TITLE = md([
    "# Fire model v6 — bootstrap + Drive-resilient fine-tune\n",
    "\n",
    "Builds the dataset **on the Colab machine** (the corpus is downloaded from HuggingFace —\n",
    "nothing large is uploaded) and fine-tunes **v4** (`models/fire/best.pt`).\n",
    "\n",
    "**Before you start:** put `colab_upload.zip` (built locally by\n",
    "`dev_scripts/pack_colab_upload.sh`, ~83 MB) in `MyDrive/colab-data/v6-training/`.\n",
    "\n",
    "- **Every stage is logged to Drive** at `MyDrive/colab-data/v6-training/logs/<stage>.log`.\n",
    "- **Every run artifact** lands in `MyDrive/colab-data/v6-training/runs/<name>/`\n",
    "  (`train.log`, `results.csv`, `args.yaml`, `weights/{last,best}.pt`), refreshed every epoch.\n",
    "- **Training is detached**: closing VS Code or the tab does not stop it, and **Cell 13**\n",
    "  re-attaches by reading `results.csv` / the log instead of the notebook's output stream.\n",
    "\n",
    "Plan: `plans/fire-model-v6-fireviewer-training.md`.\n",
])

C_SETUP = code([
    "# Cell 1 - deps + GPU\n",
    "!nvidia-smi\n",
    "!pip -q install --upgrade ultralytics pyarrow huggingface_hub\n",
    "import torch, ultralytics, pyarrow, huggingface_hub\n",
    "print('ultralytics', ultralytics.__version__, '| pyarrow', pyarrow.__version__)\n",
    "print('torch', torch.__version__, '| cuda', torch.cuda.is_available())\n",
    "assert torch.cuda.is_available(), 'pick a GPU runtime (Runtime -> Change runtime type)'\n",
])

C_CONFIG = code([
    "# Cell 2 - config\n",
    "DRIVE_DIR  = '/content/drive/MyDrive/colab-data/v6-training'\n",
    "DRIVE_ZIP  = DRIVE_DIR + '/colab_upload.zip'\n",
    "HF_REPO    = 'fireviewer/fire-smoke-detection-corpus-v1'\n",
    "CACHE      = '/content/fvcache'     # parquet download (temporary)\n",
    "YOLO_DS    = '/content/fv_yolo'     # converted YOLO dataset (train/ + val/)\n",
    "DUPS       = '/content/fv_dups'     # near-duplicates moved out of train by dedup\n",
    "BALANCE_OUT= '/content/fv_balance_out'   # background moved out by the balancer\n",
    "UPLOAD     = '/content/upload'      # unpacked colab_upload.zip\n",
    "LOGS       = DRIVE_DIR + '/logs'    # debug logs for every stage\n",
    "\n",
    "# --- where run artifacts live ---\n",
    "RUNS        = DRIVE_DIR + '/runs'   # every artifact is MIRRORED here every epoch\n",
    "LOCAL_RUNS  = '/content/runs'       # fast local project dir (Drive FUSE is slow)\n",
    "RUNS_MODE   = 'local_mirror'        # 'local_mirror' (default) | 'drive'\n",
    "LOG_LOCAL   = '/content/train.log'  # detached trainer stdout (mirrored to Drive)\n",
    "NAME        = 'v6-fireviewer'\n",
    "LOG_DRIVE   = RUNS + '/' + NAME + '/train.log'\n",
    "PIDFILE     = '/content/train.pid'\n",
    "NAMES       = {0: 'fire', 1: 'other', 2: 'smoke'}   # class contract: every cell needs it\n",
    "\n",
    "# --- dataset build ---\n",
    "DEDUP_TRAIN   = True    # move near-duplicate TRAIN frames out (val is never touched)\n",
    "DEDUP_HAMMING = 8       # dHash distance; 6 conservative, 10 aggressive\n",
    "BALANCE_MODE  = 'auto'  # 'auto' | 'off'  (rebalance after dedup, Cell 8)\n",
    "BALANCE_RATIO = 1.5     # rebalance when the fire:smoke image ratio exceeds this\n",
    "ADD_NEGATIVES = True    # inject our ~841 domain negatives into TRAIN\n",
    "FREE_CACHE    = True    # delete the ~25 GB parquet cache before training\n",
    "VAL_LIMIT     = 0       # 0 = keep all 19,209 val images. Validation runs 601 batches EVERY\n",
    "                        # epoch (the first pass measured ~7.6 s/it), which can dwarf a\n",
    "                        # ~4.6 min training epoch; set e.g. 3000 to trim val for early\n",
    "                        # stopping - the real judgement happens locally anyway.\n",
    "\n",
    "# --- training ---\n",
    "EPOCHS   = 15     # ~33k images after dedup; patience stops early\n",
    "BATCH    = 16     # 32 on an L4, 64+ on an A100; 8 if a T4 OOMs\n",
    "IMGSZ    = 640    # matches production input\n",
    "FREEZE   = 10     # keep early backbone (less forgetting); 0 = full fine-tune\n",
    "LR0      = 0.001  # low LR for a pretrained fine-tune\n",
    "PATIENCE = 5      # early stop on the held-out val split\n",
    "SAVE_PERIOD = 1   # checkpoint every epoch -> survives a recycle\n",
])

C_LOGGING = code([
    "# Cell 3 - debug logging: mirror every stage's stdout into <DRIVE>/logs/<stage>.log\n",
    "import contextlib, os, sys, time\n",
    "from google.colab import drive\n",
    "\n",
    "drive.mount('/content/drive')\n",
    "os.makedirs(LOGS, exist_ok=True)\n",
    "\n",
    "class _Tee:\n",
    "    \"\"\"Duplicate everything written to stdout into a file (line-buffered) on Drive.\"\"\"\n",
    "    def __init__(self, path):\n",
    "        self.path = path\n",
    "        self.f = open(path, 'a', buffering=1)\n",
    "        self.out = sys.__stdout__\n",
    "    def write(self, s):\n",
    "        self.f.write(s)\n",
    "        try:\n",
    "            self.out.write(s)\n",
    "        except Exception:\n",
    "            pass\n",
    "    def flush(self):\n",
    "        try:\n",
    "            self.f.flush()\n",
    "            self.out.flush()\n",
    "        except Exception:\n",
    "            pass\n",
    "    def close(self):\n",
    "        try:\n",
    "            self.f.close()\n",
    "        except Exception:\n",
    "            pass\n",
    "\n",
    "@contextlib.contextmanager\n",
    "def drive_log(stage):\n",
    "    \"\"\"with drive_log('07_dedup'): <work>  -> full stdout also lands in <DRIVE>/logs/.\"\"\"\n",
    "    path = os.path.join(LOGS, stage + '.log')\n",
    "    tee = _Tee(path)\n",
    "    tee.write('\\n' + '=' * 72 + '\\n[%s] started %s\\n' % (stage, time.strftime('%Y-%m-%d %H:%M:%S'))\n",
    "              + '=' * 72 + '\\n')\n",
    "    try:\n",
    "        # stderr too: a traceback is printed by IPython to stderr, so without this the\n",
    "        # Drive log would show 'started'/'finished' and NOTHING in between on a crash.\n",
    "        with contextlib.redirect_stdout(tee), contextlib.redirect_stderr(tee):\n",
    "            yield path\n",
    "    finally:\n",
    "        tee.write('[%s] finished %s\\n' % (stage, time.strftime('%H:%M:%S')))\n",
    "        tee.close()\n",
    "    print('log ->', path)\n",
    "\n",
    "print('logs ->', LOGS)\n",
])

C_BUNDLE = code([
    "# Cell 4 - unpack the (small) upload bundle from Drive (self-healing)\n",
    "import glob, os, shutil, zipfile\n",
    "\n",
    "# everything the later cells need; a STALE unpack from an older bundle is replaced\n",
    "# automatically instead of being silently reused (that trap cost a run once).\n",
    "REQUIRED = ['model/best.pt', 'scripts/colab_train_v6.py',\n",
    "            'scripts/prep_fireviewer_dataset.py', 'negatives', 'audit']\n",
    "os.makedirs(os.path.join(RUNS, NAME), exist_ok=True)   # the log needs a home on Drive\n",
    "\n",
    "missing = [r for r in REQUIRED if not os.path.exists(os.path.join(UPLOAD, r))]\n",
    "if missing:\n",
    "    assert os.path.exists(DRIVE_ZIP), ('missing ' + DRIVE_ZIP +\n",
    "        ' - build it with dev_scripts/pack_colab_upload.sh and upload it to ' + DRIVE_DIR)\n",
    "    print('(re)extracting bundle; missing so far:', ', '.join(missing))\n",
    "    if os.path.isdir(UPLOAD):\n",
    "        shutil.rmtree(UPLOAD)\n",
    "    os.makedirs(UPLOAD, exist_ok=True)\n",
    "    with zipfile.ZipFile(DRIVE_ZIP) as z:\n",
    "        z.extractall(UPLOAD)\n",
    "        if 'BUNDLE.txt' in z.namelist():\n",
    "            print('--- bundle provenance ---')\n",
    "            print(z.read('BUNDLE.txt').decode().strip())\n",
    "            print('-------------------------')\n",
    "\n",
    "missing = [r for r in REQUIRED if not os.path.exists(os.path.join(UPLOAD, r))]\n",
    "assert not missing, ('bundle is missing ' + ', '.join(missing) +\n",
    "                     ' - rebuild with dev_scripts/pack_colab_upload.sh, re-upload it to '\n",
    "                     + DRIVE_DIR + ', then re-run this cell')\n",
    "print('bundle contents:', sorted(os.listdir(UPLOAD)))\n",
    "print('base:', UPLOAD + '/model/best.pt')\n",
    "print('runs:', RUNS, '| logs:', LOGS)\n",
])

C_DOWNLOAD = code([
    "# Cell 5 - download ONLY the parquet we train on (train + validation), idempotently\n",
    "from huggingface_hub import snapshot_download\n",
    "\n",
    "with drive_log('05_download'):\n",
    "    if glob.glob(CACHE + '/data/train/*.parquet'):\n",
    "        print('corpus already downloaded ->', CACHE)\n",
    "    else:\n",
    "        snapshot_download(HF_REPO, repo_type='dataset', local_dir=CACHE,\n",
    "                          allow_patterns=['data/train/*', 'data/validation/*'])\n",
    "    for sp in ('train', 'validation'):\n",
    "        print('  %-11s %d parquet shard(s)'\n",
    "              % (sp, len(glob.glob('%s/data/%s/*.parquet' % (CACHE, sp)))))\n",
    "    print('NOTE: the corpus test split is deliberately NOT downloaded - judge locally.')\n",
])

C_CONVERT = code([
    "# Cell 6 - convert parquet -> YOLO on the Colab disk (reuses the repo converter)\n",
    "import subprocess, sys\n",
    "\n",
    "with drive_log('06_convert'):\n",
    "    conv = UPLOAD + '/scripts/prep_fireviewer_dataset.py'\n",
    "    if os.path.isfile(YOLO_DS + '/data.yaml'):\n",
    "        print('already converted ->', YOLO_DS)\n",
    "    else:\n",
    "        if os.path.isdir(YOLO_DS) and glob.glob(YOLO_DS + '/train/images/*'):\n",
    "            raise SystemExit('partial ' + YOLO_DS + ' - run `!rm -rf ' + YOLO_DS + '` then re-run')\n",
    "        subprocess.run([sys.executable, conv, '--corpus', CACHE, '--out', YOLO_DS,\n",
    "                        '--splits', 'train,validation'], check=True)\n",
    "    print(open(YOLO_DS + '/data.yaml').read())\n",
])

C_DEDUP = code([
    "# Cell 7 - dedup TRAIN in place: move near-duplicate frames out (val untouched)\n",
    "# The corpus is already image-unique and cross-source deduped, but its video sources are\n",
    "# sampled per frame (pyro-sdis ~907 imgs/clip, boreal ~1420), so within-clip near-dups\n",
    "# dominate. Comparisons are bounded by the corpus' own split_group (one clip per group).\n",
    "#\n",
    "# Progress   : a line every PROGRESS_EVERY images (and every 200 groups); each line is also\n",
    "#              appended to the Drive log, so keep the interval modest.\n",
    "# Live status: <LOGS>/07_dedup.status.txt, rewritten atomically every STATUS_EVERY_S, so the\n",
    "#              run can be watched from Drive without this notebook's stdout.\n",
    "# Robustness : an unreadable image (truncated / 0-byte = the full-disk signature) is\n",
    "#              quarantined instead of killing the run, and ANY exception is printed into\n",
    "#              this cell's stdout - i.e. into the Drive log. (The first version silently\n",
    "#              died here: a traceback goes to stderr, which the log did not capture.)\n",
    "import collections, csv, hashlib, os, shutil, time, traceback\n",
    "from PIL import Image\n",
    "\n",
    "PROGRESS_EVERY = 1000    # images between progress lines\n",
    "STATUS_EVERY_S = 20      # min seconds between status-file rewrites\n",
    "SKIP_BROKEN    = True    # False -> abort on the first unreadable image\n",
    "BROKEN_OUT     = '/content/fv_broken'\n",
    "\n",
    "with drive_log('07_dedup'):\n",
    "    t0 = time.time()\n",
    "    STATUS_FILE = LOGS + '/07_dedup.status.txt'\n",
    "\n",
    "    def _dhash(path):\n",
    "        im = Image.open(path).convert('L').resize((9, 8), Image.LANCZOS)\n",
    "        px = list(im.getdata())\n",
    "        bits = 0\n",
    "        for r in range(8):\n",
    "            for c in range(8):\n",
    "                bits = (bits << 1) | (1 if px[r * 9 + c] < px[r * 9 + c + 1] else 0)\n",
    "        return bits\n",
    "\n",
    "    st = {'t': 0.0}\n",
    "\n",
    "    def _status(state, **kw):\n",
    "        tmp = STATUS_FILE + '.tmp'\n",
    "        with open(tmp, 'w') as fh:\n",
    "            for k, v in dict(stage='07_dedup', state=state, **kw).items():\n",
    "                fh.write('%s: %s\\n' % (k, v))\n",
    "        os.replace(tmp, STATUS_FILE)     # atomic: a reader never sees a half file\n",
    "\n",
    "    if not DEDUP_TRAIN:\n",
    "        print('DEDUP_TRAIN=False -> skipped (val is never deduped regardless)')\n",
    "    else:\n",
    "        os.makedirs(DUPS + '/images', exist_ok=True)\n",
    "        os.makedirs(DUPS + '/labels', exist_ok=True)\n",
    "\n",
    "        groups = collections.defaultdict(list)\n",
    "        with open(YOLO_DS + '/manifest.csv') as fh:\n",
    "            for r in csv.DictReader(fh):\n",
    "                if r['split'] == 'train':\n",
    "                    groups[r['split_group']].append(r['stem'])\n",
    "        total = sum(len(v) for v in groups.values())\n",
    "        print('groups=%d  manifest images=%d  hamming<=%d  progress every %d imgs'\n",
    "              % (len(groups), total, DEDUP_HAMMING, PROGRESS_EVERY))\n",
    "        print('full log    -> %s' % LOG_DRIVE)\n",
    "        print('live status -> %s' % STATUS_FILE)\n",
    "\n",
    "        done = kept_total = moved_total = broken = missing = 0\n",
    "        keep_md5 = set()\n",
    "        ok, err, gi = True, '', 0\n",
    "        _status('running', done=0, total=total, kept=0, moved=0, broken=0,\n",
    "                elapsed_s=0, eta_s='?', group='0/%d' % len(groups))\n",
    "\n",
    "        try:\n",
    "            for gi, (grp, stems) in enumerate(groups.items(), 1):\n",
    "                kept = []                        # [(dhash, stem), ...] within this clip\n",
    "                for stem in stems:\n",
    "                    img = YOLO_DS + '/train/images/' + stem + '.jpg'\n",
    "                    done += 1\n",
    "                    if not os.path.exists(img):\n",
    "                        missing += 1\n",
    "                        continue\n",
    "                    try:\n",
    "                        h = _dhash(img)\n",
    "                    except Exception as e:\n",
    "                        broken += 1\n",
    "                        if not SKIP_BROKEN:\n",
    "                            raise\n",
    "                        os.makedirs(BROKEN_OUT + '/images', exist_ok=True)\n",
    "                        print('  ! unreadable %s (%s) -> %s'\n",
    "                              % (stem[:16], type(e).__name__, BROKEN_OUT), flush=True)\n",
    "                        try:\n",
    "                            shutil.move(img, BROKEN_OUT + '/images/' + stem + '.jpg')\n",
    "                        except OSError:\n",
    "                            pass\n",
    "                        continue\n",
    "\n",
    "                    m = hashlib.md5(open(img, 'rb').read()).hexdigest()\n",
    "                    dup = (m in keep_md5) or any(\n",
    "                        bin(kh ^ h).count('1') <= DEDUP_HAMMING for kh, _ in kept)\n",
    "                    if dup:\n",
    "                        shutil.move(img, DUPS + '/images/' + stem + '.jpg')\n",
    "                        lp = YOLO_DS + '/train/labels/' + stem + '.txt'\n",
    "                        if os.path.exists(lp):\n",
    "                            shutil.move(lp, DUPS + '/labels/' + stem + '.txt')\n",
    "                        moved_total += 1\n",
    "                    else:\n",
    "                        keep_md5.add(m)\n",
    "                        kept.append((h, stem))\n",
    "                        kept_total += 1\n",
    "\n",
    "                    if done % PROGRESS_EVERY == 0:\n",
    "                        el = time.time() - t0\n",
    "                        rate = done / el if el else 0.0\n",
    "                        eta = (total - done) / rate if rate else 0\n",
    "                        msg = ('  %6d/%d %5.1f%% | kept %d moved %d broken %d'\n",
    "                               ' | %.0f img/s | ETA %dm%02ds | group %d/%d')\n",
    "                        print(msg % (done, total,\n",
    "                                     100.0 * done / total if total else 100.0,\n",
    "                                     kept_total, moved_total, broken, rate,\n",
    "                                     int(eta) // 60, int(eta) % 60, gi, len(groups)),\n",
    "                              flush=True)\n",
    "                        if time.time() - st['t'] >= STATUS_EVERY_S:\n",
    "                            st['t'] = time.time()\n",
    "                            _status('running', done=done, total=total, kept=kept_total,\n",
    "                                    moved=moved_total, broken=broken, elapsed_s=int(el),\n",
    "                                    eta_s=int(eta), group='%d/%d' % (gi, len(groups)))\n",
    "\n",
    "                if gi % 200 == 0:                # visible even for tiny groups\n",
    "                    el = time.time() - t0\n",
    "                    print('  ... %d/%d groups | kept %d moved %d broken %d | %.1f min'\n",
    "                          % (gi, len(groups), kept_total, moved_total, broken, el / 60.0),\n",
    "                          flush=True)\n",
    "        except Exception:\n",
    "            ok = False\n",
    "            err = traceback.format_exc()\n",
    "            print('[07_dedup] FAILED after %d/%d images (group %d/%d)'\n",
    "                  % (done, total, gi, len(groups)), flush=True)\n",
    "            print(err, flush=True)               # printed -> lands in the Drive log\n",
    "\n",
    "        el = time.time() - t0\n",
    "        _status('ok' if ok else 'failed', done=done, total=total, kept=kept_total,\n",
    "                moved=moved_total, broken=broken, missing=missing, elapsed_s=int(el),\n",
    "                error=(err.strip().splitlines()[-1] if err else ''))\n",
    "\n",
    "        print()\n",
    "        print('train kept %d | near-dups moved %d | unreadable %d | missing %d | %.1f min'\n",
    "              % (kept_total, moved_total, broken, missing, el / 60.0))\n",
    "        print('val untouched:', len(os.listdir(YOLO_DS + '/val/images')), 'images')\n",
    "        print('status -> %s' % STATUS_FILE)\n",
])

C_BALANCE = code([
    "# Cell 8 - rebalance TRAIN when dedup hit one class harder than the other\n",
    "# Dedup removes the smoke-heavy VIDEO sources hardest (measured: smoke boxes -69% vs\n",
    "# fire -37%), so the mix drifts. This restores the minority class FROM THE DEDUP PILE\n",
    "# (nothing is deleted - /content/fv_dups still holds every frame), spreading the restored\n",
    "# frames round-robin across clips so we add diversity, not clones. It then caps the\n",
    "# background share, moving the excess to /content/fv_balance_out (reversible).\n",
    "BALANCE_PER_GROUP = 25      # max frames restored per clip (diversity guard)\n",
    "BALANCE_MAX_BG    = 0.60    # cap background share of TRAIN\n",
    "\n",
    "with drive_log('08_balance'):\n",
    "    ti, tl = YOLO_DS + '/train/images', YOLO_DS + '/train/labels'\n",
    "    di, dl = DUPS + '/images', DUPS + '/labels'\n",
    "    os.makedirs(BALANCE_OUT + '/images', exist_ok=True)\n",
    "    os.makedirs(BALANCE_OUT + '/labels', exist_ok=True)\n",
    "\n",
    "    def classes_of(label_dir, stem):\n",
    "        p = os.path.join(label_dir, stem + '.txt')\n",
    "        out = set()\n",
    "        if os.path.isfile(p):\n",
    "            for row in open(p):\n",
    "                parts = row.split()\n",
    "                if parts:\n",
    "                    out.add(int(float(parts[0])))\n",
    "        return out\n",
    "\n",
    "    def counts(img_dir, lbl_dir):\n",
    "        c = collections.Counter()\n",
    "        for f in os.listdir(img_dir):\n",
    "            cl = classes_of(lbl_dir, os.path.splitext(f)[0])\n",
    "            if not cl:\n",
    "                c['background'] += 1\n",
    "            for k in cl:\n",
    "                c[NAMES[k]] += 1\n",
    "        return c\n",
    "\n",
    "    grp_of = {}\n",
    "    if os.path.isfile(YOLO_DS + '/manifest.csv'):\n",
    "        with open(YOLO_DS + '/manifest.csv') as fh:\n",
    "            for r in csv.DictReader(fh):\n",
    "                if r['split'] == 'train':\n",
    "                    grp_of[r['stem']] = r['split_group']\n",
    "\n",
    "    before = counts(ti, tl)\n",
    "    n_before = len(os.listdir(ti))\n",
    "    print('BEFORE images=%d' % n_before)\n",
    "    print('  class images : fire=%d smoke=%d background=%d'\n",
    "          % (before['fire'], before['smoke'], before['background']))\n",
    "\n",
    "    pair = {'fire': before['fire'], 'smoke': before['smoke']}\n",
    "    hi = max(pair, key=pair.get)\n",
    "    lo = min(pair, key=pair.get)\n",
    "    ratio = pair[hi] / max(1, pair[lo])\n",
    "    target = int(pair[hi] / BALANCE_RATIO)\n",
    "    need = max(0, target - pair[lo])\n",
    "    print('  %s:%s = %d:%d (ratio %.2f, limit %.2f) -> restore %d %s frames'\n",
    "          % (hi, lo, pair[hi], pair[lo], ratio, BALANCE_RATIO, need, lo))\n",
    "\n",
    "    restored = 0\n",
    "    if BALANCE_MODE == 'off':\n",
    "        print('  BALANCE_MODE=off -> no restore')\n",
    "    elif ratio <= BALANCE_RATIO or need == 0:\n",
    "        print('  classes are within the ratio limit -> no restore needed')\n",
    "    else:\n",
    "        lo_id = 0 if lo == 'fire' else 2\n",
    "        by_grp = collections.defaultdict(list)\n",
    "        for f in sorted(os.listdir(di)):\n",
    "            stem = os.path.splitext(f)[0]\n",
    "            if lo_id in classes_of(dl, stem):\n",
    "                by_grp[grp_of.get(stem, stem)].append(stem)\n",
    "        per = {g: 0 for g in by_grp}\n",
    "        progress = True\n",
    "        while restored < need and progress:\n",
    "            progress = False\n",
    "            for g in sorted(by_grp):\n",
    "                if restored >= need:\n",
    "                    break\n",
    "                if per[g] >= BALANCE_PER_GROUP or not by_grp[g]:\n",
    "                    continue\n",
    "                stem = by_grp[g].pop(0)\n",
    "                shutil.move(os.path.join(di, stem + '.jpg'), os.path.join(ti, stem + '.jpg'))\n",
    "                lp = os.path.join(dl, stem + '.txt')\n",
    "                if os.path.exists(lp):\n",
    "                    shutil.move(lp, os.path.join(tl, stem + '.txt'))\n",
    "                per[g] += 1\n",
    "                restored += 1\n",
    "                progress = True\n",
    "        print('  restored %d %s frames from the dedup pile, spread over %d clips'\n",
    "              % (restored, lo, sum(1 for v in per.values() if v)))\n",
    "        if restored < need:\n",
    "            print('  NOTE: only %d of %d available (per-clip cap %d / empty pile)'\n",
    "                  % (restored, need, BALANCE_PER_GROUP))\n",
    "\n",
    "    n_now = len(os.listdir(ti))\n",
    "    bg_now = before['background']\n",
    "    bg_share = bg_now / n_now if n_now else 0.0\n",
    "    moved_bg = 0\n",
    "    if bg_share > BALANCE_MAX_BG:\n",
    "        # solve bg_new = BALANCE_MAX_BG * (bg_new + nonbg): moving images out also\n",
    "        # shrinks the denominator, so the naive formula would under-move.\n",
    "        nonbg = max(0, n_now - bg_now)\n",
    "        max_bg = int(BALANCE_MAX_BG * nonbg / (1.0 - BALANCE_MAX_BG))\n",
    "        excess = max(0, bg_now - max_bg)\n",
    "        print('  background share %.1f%% > %.0f%% -> moving %d out'\n",
    "              % (100 * bg_share, 100 * BALANCE_MAX_BG, excess))\n",
    "        for f in sorted(os.listdir(ti)):\n",
    "            if moved_bg >= excess:\n",
    "                break\n",
    "            stem = os.path.splitext(f)[0]\n",
    "            if classes_of(tl, stem):        # only ever move pure background\n",
    "                continue\n",
    "            shutil.move(os.path.join(ti, f), os.path.join(BALANCE_OUT, 'images', f))\n",
    "            lp = os.path.join(tl, stem + '.txt')\n",
    "            if os.path.exists(lp):\n",
    "                shutil.move(lp, os.path.join(BALANCE_OUT, 'labels', stem + '.txt'))\n",
    "            moved_bg += 1\n",
    "        print('  background moved out: %d -> %s' % (moved_bg, BALANCE_OUT))\n",
    "    else:\n",
    "        print('  background share %.1f%% <= %.0f%% -> kept as-is'\n",
    "              % (100 * bg_share, 100 * BALANCE_MAX_BG))\n",
    "\n",
    "    after = counts(ti, tl)\n",
    "    print('AFTER images=%d' % len(os.listdir(ti)))\n",
    "    print('  class images : fire=%d smoke=%d background=%d'\n",
    "          % (after['fire'], after['smoke'], after['background']))\n",
    "    print('  delta        : fire %+d smoke %+d background %+d'\n",
    "          % (after['fire'] - before['fire'], after['smoke'] - before['smoke'],\n",
    "             after['background'] - before['background']))\n",
    "    print('re-run Cell 9 to verify the structure')\n",
])

C_VERIFY = code([
    "# Cell 9 - verify the corpus structure after dedup + balance (read-only, ~10-30 s)\n",
    "import collections, csv, os, random, shutil as _shutil\n",
    "from PIL import Image\n",
    "\n",
    "EXT = ('.jpg', '.jpeg', '.png', '.bmp', '.webp')\n",
    "warn, fail = [], []\n",
    "\n",
    "with drive_log('09_verify'):\n",
    "    for _sp in ('train', 'val'):                  # stale caches would mask changes\n",
    "        _c = os.path.join(YOLO_DS, _sp, 'labels.cache')\n",
    "        if os.path.exists(_c):\n",
    "            os.remove(_c)\n",
    "\n",
    "    def split_stats(sp):\n",
    "        idir, ldir = os.path.join(YOLO_DS, sp, 'images'), os.path.join(YOLO_DS, sp, 'labels')\n",
    "        imgs = sorted(f for f in os.listdir(idir) if f.lower().endswith(EXT))\n",
    "        boxes, withcls = collections.Counter(), collections.Counter()\n",
    "        missing = bad = oor = 0\n",
    "        for f in imgs:\n",
    "            stem = os.path.splitext(f)[0]\n",
    "            lb = os.path.join(ldir, stem + '.txt')\n",
    "            if not os.path.isfile(lb):\n",
    "                missing += 1\n",
    "                continue\n",
    "            present, n = set(), 0\n",
    "            for row in open(lb):\n",
    "                parts = row.split()\n",
    "                if not parts:\n",
    "                    continue\n",
    "                if len(parts) != 5:\n",
    "                    bad += 1\n",
    "                    continue\n",
    "                try:\n",
    "                    c = int(float(parts[0]))\n",
    "                    vals = [float(v) for v in parts[1:]]\n",
    "                except ValueError:\n",
    "                    bad += 1\n",
    "                    continue\n",
    "                if c not in NAMES:\n",
    "                    bad += 1\n",
    "                    continue\n",
    "                if any(v < 0.0 or v > 1.0 for v in vals):\n",
    "                    oor += 1\n",
    "                boxes[NAMES[c]] += 1\n",
    "                present.add(NAMES[c])\n",
    "                n += 1\n",
    "            for k in present:                 # count each class ONCE per image\n",
    "                withcls[k] += 1\n",
    "            if n == 0:\n",
    "                withcls['background'] += 1\n",
    "        labels = [f for f in os.listdir(ldir) if f.endswith('.txt')]\n",
    "        stems = {os.path.splitext(f)[0] for f in imgs}\n",
    "        orphan = sum(1 for f in labels if os.path.splitext(f)[0] not in stems)\n",
    "        return dict(n=len(imgs), labels=len(labels), boxes=boxes, withcls=withcls,\n",
    "                    missing=missing, orphan=orphan, bad=bad, oor=oor)\n",
    "\n",
    "    print('=' * 74)\n",
    "    print('Corpus after dedup + balance ->', YOLO_DS)\n",
    "    print('=' * 74)\n",
    "    st = {}\n",
    "    for sp in ('train', 'val'):\n",
    "        s = st[sp] = split_stats(sp)\n",
    "        print()\n",
    "        print('[%s] images=%d  label files=%d' % (sp, s['n'], s['labels']))\n",
    "        print('   boxes     : ' + (', '.join(k + '=' + str(v) for k, v in sorted(s['boxes'].items())) or '-'))\n",
    "        print('   images w/ : ' + (', '.join(k + '=' + str(v) for k, v in sorted(s['withcls'].items())) or '-'))\n",
    "        print('   integrity : missing_label=%d orphan_labels=%d malformed_rows=%d coords_out_of_range=%d'\n",
    "              % (s['missing'], s['orphan'], s['bad'], s['oor']))\n",
    "        if s['missing'] or s['orphan'] or s['bad'] or s['oor']:\n",
    "            fail.append(sp + ': integrity problems')\n",
    "        for cls in ('fire', 'smoke'):\n",
    "            if s['boxes'].get(cls, 0) == 0:\n",
    "                (fail if sp == 'val' else warn).append(sp + ': no ' + cls + ' boxes')\n",
    "\n",
    "    tr = st['train']\n",
    "    if tr['n'] and tr['withcls'].get('background', 0) / tr['n'] > 0.80:\n",
    "        warn.append('train background share %.1f%%'\n",
    "                    % (100.0 * tr['withcls']['background'] / tr['n']))\n",
    "    fr, sm = tr['boxes'].get('fire', 0), tr['boxes'].get('smoke', 0)\n",
    "    if fr and sm and max(fr, sm) / min(fr, sm) > 2.0:\n",
    "        warn.append('train box imbalance fire=%d smoke=%d (ratio %.2f) - consider Cell 8'\n",
    "                    % (fr, sm, max(fr, sm) / min(fr, sm)))\n",
    "\n",
    "    mf = os.path.join(YOLO_DS, 'manifest.csv')\n",
    "    if os.path.isfile(mf):\n",
    "        have = {os.path.splitext(f)[0] for f in os.listdir(YOLO_DS + '/train/images')}\n",
    "        before, after = collections.Counter(), collections.Counter()\n",
    "        gb, ga = collections.Counter(), collections.Counter()\n",
    "        with open(mf) as fh:\n",
    "            for r in csv.DictReader(fh):\n",
    "                if r['split'] != 'train':\n",
    "                    continue\n",
    "                gb[r['split_group']] += 1\n",
    "                before[r['source_name']] += 1\n",
    "                if r['stem'] in have:\n",
    "                    after[r['source_name']] += 1\n",
    "                    ga[r['split_group']] += 1\n",
    "        print()\n",
    "        print('per-source survival (train):')\n",
    "        print('   %-12s %8s %8s %9s %8s' % ('source', 'before', 'after', 'removed', 'keep'))\n",
    "        tb = ta = 0\n",
    "        for src in sorted(before):\n",
    "            b, a = before[src], after[src]\n",
    "            tb += b\n",
    "            ta += a\n",
    "            print('   %-12s %8d %8d %9d %7.1f%%' % (src, b, a, b - a, 100.0 * a / b if b else 0.0))\n",
    "        print('   %-12s %8d %8d %9d %7.1f%%'\n",
    "              % ('TOTAL', tb, ta, tb - ta, 100.0 * ta / tb if tb else 0.0))\n",
    "        live = [g for g, n in ga.items() if n]\n",
    "        print()\n",
    "        print('clips still present : %d / %d' % (len(live), len(gb)))\n",
    "        _m = 'largest live clip   : %d frames (was %d)'\n",
    "        print(_m % (max(ga.values()) if ga else 0, max(gb.values()) if gb else 0))\n",
    "        if ga and gb and max(ga.values()) > 0.5 * max(gb.values()):\n",
    "            _m2 = 'largest live clip is %.0f%% of the original - dedup may not have bitten'\n",
    "            warn.append(_m2 % (100.0 * max(ga.values()) / max(gb.values())))\n",
    "    else:\n",
    "        warn.append('manifest.csv missing - per-source survival not computed')\n",
    "\n",
    "    idir = os.path.join(YOLO_DS, 'train', 'images')\n",
    "    files = sorted(os.listdir(idir))\n",
    "    random.seed(0)\n",
    "    sample = random.sample(files, min(800, len(files)))\n",
    "    if '_dhash' in globals():\n",
    "        hs = [_dhash(os.path.join(idir, f)) for f in sample]\n",
    "        near = 0\n",
    "        for i in range(len(hs)):\n",
    "            for j in range(i + 1, len(hs)):\n",
    "                if bin(hs[i] ^ hs[j]).count('1') <= DEDUP_HAMMING:\n",
    "                    near += 1\n",
    "        pairs = len(hs) * (len(hs) - 1) // 2\n",
    "        _m3 = 'residual near-dups: %d pair(s) <=%d among %d random train images (%.3f%% of %d pairs)'\n",
    "        print()\n",
    "        print(_m3 % (near, DEDUP_HAMMING, len(hs),\n",
    "                     100.0 * near / pairs if pairs else 0.0, pairs))\n",
    "        if pairs and near / pairs > 0.005:\n",
    "            warn.append('%d residual near-dup pair(s) (%.3f%%)' % (near, 100.0 * near / pairs))\n",
    "    else:\n",
    "        print('\\n(residual check skipped: run Cell 7 first - _dhash not defined)')\n",
    "\n",
    "    # image sanity: a full Colab disk can leave 0-byte / truncated JPEGs behind, which\n",
    "    # YOLO would happily count as samples while PIL/training chokes on them later.\n",
    "    zero = 0\n",
    "    for _sp in ('train', 'val'):\n",
    "        _idir = os.path.join(YOLO_DS, _sp, 'images')\n",
    "        for _f in os.listdir(_idir):\n",
    "            if os.path.getsize(os.path.join(_idir, _f)) == 0:\n",
    "                zero += 1\n",
    "    random.seed(1)\n",
    "    broken = 0\n",
    "    for _f in random.sample(sorted(os.listdir(idir)), min(300, len(files))):\n",
    "        try:\n",
    "            with Image.open(os.path.join(idir, _f)) as _im:\n",
    "                _im.verify()\n",
    "        except Exception:\n",
    "            broken += 1\n",
    "    print()\n",
    "    print('image sanity : 0-byte=%d  unreadable=%d (of %d sampled)'\n",
    "          % (zero, broken, min(300, len(files))))\n",
    "    if zero or broken:\n",
    "        fail.append('image sanity: %d 0-byte, %d unreadable - check disk then re-run Cells 5-6'\n",
    "                    % (zero, broken))\n",
    "\n",
    "    print()\n",
    "    print(open(os.path.join(YOLO_DS, 'data.yaml')).read().strip())\n",
    "    dups = len(os.listdir(DUPS + '/images')) if os.path.isdir(DUPS + '/images') else 0\n",
    "    print()\n",
    "    print('dups moved out : %d images in %s' % (dups, DUPS))\n",
    "    print('/content free  : %.1f GB' % (_shutil.disk_usage('/content').free / 1e9))\n",
    "    print()\n",
    "    print('RESULT: ' + ('FAIL - ' + '; '.join(fail) if fail else\n",
    "                        ('WARN - ' + '; '.join(warn) if warn else 'PASS')))\n",
])

C_NEGATIVES = code([
    "# Cell 10 - add our domain negatives to TRAIN (empty label = background), free the cache\n",
    "with drive_log('10_negatives'):\n",
    "    if ADD_NEGATIVES:\n",
    "        neg = UPLOAD + '/negatives'\n",
    "        ti, tl = YOLO_DS + '/train/images', YOLO_DS + '/train/labels'\n",
    "        added = 0\n",
    "        for f in sorted(glob.glob(neg + '/*')):\n",
    "            if os.path.splitext(f)[1].lower() not in ('.jpg', '.jpeg', '.png'):\n",
    "                continue\n",
    "            base = os.path.basename(f)\n",
    "            if not os.path.exists(os.path.join(ti, base)):\n",
    "                shutil.copy2(f, os.path.join(ti, base))\n",
    "            open(os.path.join(tl, os.path.splitext(base)[0] + '.txt'), 'w').close()\n",
    "            added += 1\n",
    "        print('negatives added to TRAIN:', added)\n",
    "    else:\n",
    "        print('ADD_NEGATIVES=False -> corpus-only run')\n",
    "    print('audit set (our real fires, HELD OUT):', UPLOAD + '/audit',\n",
    "          len(glob.glob(UPLOAD + '/audit/*')), 'imgs')\n",
    "    print('train images now:', len(os.listdir(YOLO_DS + '/train/images')))\n",
    "    if VAL_LIMIT:\n",
    "        _vi, _vl = YOLO_DS + '/val/images', YOLO_DS + '/val/labels'\n",
    "        _imgs = sorted(os.listdir(_vi))\n",
    "        if len(_imgs) > VAL_LIMIT:\n",
    "            import random as _rnd\n",
    "            _rnd.seed(0)\n",
    "            _keep = set(_rnd.sample(_imgs, VAL_LIMIT))\n",
    "            _extra = '/content/fv_val_extra'\n",
    "            os.makedirs(_extra + '/images', exist_ok=True)\n",
    "            os.makedirs(_extra + '/labels', exist_ok=True)\n",
    "            _moved = 0\n",
    "            for _f in _imgs:\n",
    "                if _f in _keep:\n",
    "                    continue\n",
    "                shutil.move(os.path.join(_vi, _f), os.path.join(_extra, 'images', _f))\n",
    "                _lp = os.path.join(_vl, os.path.splitext(_f)[0] + '.txt')\n",
    "                if os.path.exists(_lp):\n",
    "                    shutil.move(_lp, os.path.join(_extra, 'labels',\n",
    "                                                  os.path.splitext(_f)[0] + '.txt'))\n",
    "                _moved += 1\n",
    "            print('val trimmed: kept %d, moved %d -> %s' % (VAL_LIMIT, _moved, _extra))\n",
    "        else:\n",
    "            print('val already <= VAL_LIMIT (%d)' % VAL_LIMIT)\n",
    "    else:\n",
    "        print('val kept whole (%d images) - set VAL_LIMIT to trim it'\n",
    "              % len(os.listdir(YOLO_DS + '/val/images')))\n",
    "    if FREE_CACHE:\n",
    "        shutil.rmtree(CACHE, ignore_errors=True)\n",
    "        print('parquet cache removed ->', CACHE)\n",
    "    else:\n",
    "        print('FREE_CACHE=False -> keeping', CACHE, '(re-used by a second run)')\n",
    "    print('/content free: %.1f GB' % (shutil.disk_usage('/content').free / 1e9))\n",
])

C_TRAINER_CHECK = code([
    "# Cell 11 - sanity-check the detached trainer that ships in the bundle\n",
    "import subprocess, sys\n",
    "trainer = UPLOAD + '/scripts/colab_train_v6.py'\n",
    "print(subprocess.run([sys.executable, trainer, '--help'],\n",
    "                     capture_output=True, text=True).stdout[:900])\n",
])

C_LAUNCH = code([
    "# Cell 12 - LAUNCH training DETACHED (closing VS Code will NOT stop it)\n",
    "import os, subprocess, sys\n",
    "\n",
    "trainer = UPLOAD + '/scripts/colab_train_v6.py'   # defined here too: Cell 11 is optional\n",
    "assert os.path.exists(trainer), 'trainer missing from the bundle - see Cell 4'\n",
    "\n",
    "# refuse to start a second trainer on the same GPU (two would OOM)\n",
    "if os.path.exists(PIDFILE):\n",
    "    _old = int(open(PIDFILE).read().strip() or 0)\n",
    "    try:\n",
    "        os.kill(_old, 0)\n",
    "        raise SystemExit('a trainer is already running (pid %d). Watch it with Cell 13, '\n",
    "                         'or kill it first: !kill -9 %d' % (_old, _old))\n",
    "    except OSError:\n",
    "        pass\n",
    "\n",
    "os.makedirs(os.path.join(RUNS, NAME), exist_ok=True)\n",
    "args = [sys.executable, '-u', trainer,\n",
    "        '--data', YOLO_DS + '/data.yaml', '--base', UPLOAD + '/model/best.pt',\n",
    "        '--runs', RUNS, '--name', NAME, '--mode', RUNS_MODE, '--local', LOCAL_RUNS,\n",
    "        '--log', LOG_LOCAL,\n",
    "        '--epochs', str(EPOCHS), '--batch', str(BATCH), '--imgsz', str(IMGSZ),\n",
    "        '--freeze', str(FREEZE), '--lr0', str(LR0), '--patience', str(PATIENCE),\n",
    "        '--save-period', str(SAVE_PERIOD)]\n",
    "with open(LOG_LOCAL, 'ab') as lf:\n",
    "    proc = subprocess.Popen(args, cwd='/content', stdout=lf,\n",
    "                            stderr=subprocess.STDOUT, start_new_session=True)\n",
    "open(PIDFILE, 'w').write(str(proc.pid))\n",
    "print('launched pid %d (own session -> survives losing the editor/kernel)' % proc.pid)\n",
    "print('local log :', LOG_LOCAL)\n",
    "print('Drive log :', LOG_DRIVE, '(mirrored every epoch)')\n",
    "print('Drive run :', os.path.join(RUNS, NAME))\n",
    "print('next      : run Cell 13 to watch progress')\n",
])

C_STATUS = code([
    "# Cell 13 - STATUS: re-attach to the detached run (no stdout stream needed)\n",
    "import os, subprocess, time\n",
    "\n",
    "with drive_log('13_status'):\n",
    "    pid = int(open(PIDFILE).read().strip() or 0) if os.path.exists(PIDFILE) else None\n",
    "\n",
    "    def proc_state(p):\n",
    "        # os.kill(pid, 0) succeeds for a ZOMBIE too, which would fake 'RUNNING'; read\n",
    "        # /proc/<pid>/stat instead so a dead trainer is reported as dead.\n",
    "        if not p:\n",
    "            return 'no pid file'\n",
    "        try:\n",
    "            with open('/proc/%d/stat' % p) as fh:\n",
    "                fields = fh.read().split()\n",
    "            state = fields[2]\n",
    "        except (FileNotFoundError, IndexError):\n",
    "            return 'not running (no such process)'\n",
    "        if state == 'Z':\n",
    "            return 'ZOMBIE (exited - read the log tail below)'\n",
    "        return {'R': 'RUNNING', 'S': 'RUNNING (sleeping)', 'D': 'RUNNING (disk-sleep)',\n",
    "                'T': 'stopped'}.get(state, state)\n",
    "\n",
    "    print('trainer pid %s -> %s' % (pid, proc_state(pid)))\n",
    "    log_age = '%.0fs' % (time.time() - os.path.getmtime(LOG_LOCAL)) if os.path.exists(LOG_LOCAL) else 'n/a'\n",
    "    log_size = os.path.getsize(LOG_LOCAL) if os.path.exists(LOG_LOCAL) else 0\n",
    "    print('local log : %s (%d B, written %s ago)' % (LOG_LOCAL, log_size, log_age))\n",
    "    run_local = os.path.join(LOCAL_RUNS, NAME)\n",
    "    print('local run : %s%s' % (run_local, '' if os.path.isdir(run_local)\n",
    "          else '  (not created yet - training writes it after loading the model)'))\n",
    "\n",
    "    def describe(label, d):\n",
    "        print('\\n[%s] %s' % (label, d))\n",
    "        if not os.path.isdir(d):\n",
    "            print('   (missing)')\n",
    "            return\n",
    "        csvp = os.path.join(d, 'results.csv')\n",
    "        if os.path.exists(csvp):\n",
    "            rows = [r for r in open(csvp).read().splitlines() if r.strip()]\n",
    "            print('   results.csv  epochs=%d  age=%ds'\n",
    "                  % (max(0, len(rows) - 1), int(time.time() - os.path.getmtime(csvp))))\n",
    "            if len(rows) > 1:\n",
    "                print('   last row    :', rows[-1][:140])\n",
    "        w = os.path.join(d, 'weights')\n",
    "        if os.path.isdir(w):\n",
    "            for f in sorted(os.listdir(w)):\n",
    "                p = os.path.join(w, f)\n",
    "                print('   %-9s %7.1f MB  age=%ds'\n",
    "                      % (f, os.path.getsize(p) / 1e6,\n",
    "                         int(time.time() - os.path.getmtime(p))))\n",
    "\n",
    "    describe('local', os.path.join(LOCAL_RUNS, NAME))\n",
    "    describe('Drive', os.path.join(RUNS, NAME))\n",
    "\n",
    "    print('\\n-- local log tail --')\n",
    "    if os.path.exists(LOG_LOCAL):\n",
    "        print('\\n'.join(open(LOG_LOCAL, errors='replace').read().splitlines()[-15:]))\n",
    "    else:\n",
    "        print('(no log yet)')\n",
    "\n",
    "    print('\\n-- GPU --')\n",
    "    print(subprocess.run(['nvidia-smi', '--query-gpu=utilization.gpu,memory.used',\n",
    "                          '--format=csv,noheader'],\n",
    "                         capture_output=True, text=True).stdout.strip() or '(n/a)')\n",
    "    print(subprocess.run(['nvidia-smi', '--query-compute-apps=pid,used_memory',\n",
    "                          '--format=csv,noheader'],\n",
    "                         capture_output=True, text=True).stdout.strip() or '(no GPU process)')\n",
])

C_WAIT = code([
    "# Cell 13b - WAIT for the run to finish (OPTIONAL; safe to interrupt)\n",
    "# Training is DETACHED, so this cell only polls - it never blocks the trainer. Ctrl-C or\n",
    "# the notebook's stop button ends the WAIT, not the training.\n",
    "import os, time\n",
    "\n",
    "WAIT_POLL_S  = 60      # seconds between polls\n",
    "WAIT_MAX_MIN = 360     # stop waiting after this long (training keeps running)\n",
    "\n",
    "run_local = os.path.join(LOCAL_RUNS, NAME)\n",
    "run_drive = os.path.join(RUNS, NAME)\n",
    "t0 = time.time()\n",
    "n = last = 0\n",
    "state = 'no pid'\n",
    "while True:\n",
    "    rows = []\n",
    "    for _p in (os.path.join(run_local, 'results.csv'),\n",
    "               os.path.join(run_drive, 'results.csv')):\n",
    "        if os.path.exists(_p):\n",
    "            rows = [r for r in open(_p, errors='replace').read().splitlines() if r.strip()]\n",
    "            break\n",
    "    n = max(0, len(rows) - 1)                 # one row per FINISHED epoch\n",
    "    pid = int(open(PIDFILE).read().strip() or 0) if os.path.exists(PIDFILE) else 0\n",
    "    if pid and os.path.exists('/proc/%d' % pid):\n",
    "        state = 'alive'\n",
    "        try:\n",
    "            with open('/proc/%d/stat' % pid) as _fh:\n",
    "                if _fh.read().split()[2] == 'Z':\n",
    "                    state = 'ZOMBIE (exited)'\n",
    "        except IndexError:\n",
    "            pass\n",
    "    elif pid:\n",
    "        state = 'gone'\n",
    "    if n != last or state != 'alive':\n",
    "        print('[%s] epochs %d/%d | trainer %s | waiting %d min'\n",
    "              % (time.strftime('%H:%M:%S'), n, EPOCHS, state,\n",
    "                 int((time.time() - t0) / 60)), flush=True)\n",
    "        if rows:\n",
    "            print('        last row: ' + rows[-1][:120], flush=True)\n",
    "        last = n\n",
    "    if state in ('gone', 'ZOMBIE (exited)', 'no pid') or n >= EPOCHS:\n",
    "        break\n",
    "    if (time.time() - t0) > WAIT_MAX_MIN * 60:\n",
    "        print('WAIT_MAX_MIN reached - no longer waiting (training continues detached)')\n",
    "        break\n",
    "    time.sleep(WAIT_POLL_S)\n",
    "print()\n",
    "print('wait finished: %d epoch row(s), trainer %s' % (n, state))\n",
    "print('-> run finished/stopped: collect the candidate with Cell 15' if\n",
    "      (n >= EPOCHS or state in ('gone', 'ZOMBIE (exited)')) else\n",
    "      '-> still running: re-run this cell to keep waiting, or use Cell 13')\n",
])


C_RESUME = code([
    "# Cell 14 - RESUME an interrupted run (detached too). Refuses if the run FINISHED.\n",
    "# Ultralytics strips the optimizer from a completed last.pt, so resuming one would\n",
    "# silently start a brand-new run on the default dataset - hence the inspection.\n",
    "import os, shutil, subprocess, sys, torch\n",
    "\n",
    "run_local, run_drive = os.path.join(LOCAL_RUNS, NAME), os.path.join(RUNS, NAME)\n",
    "if not os.path.isdir(run_local) and os.path.isdir(run_drive):\n",
    "    # fresh VM: restore the run dir locally so the per-epoch Drive mirror keeps working\n",
    "    shutil.copytree(run_drive, run_local, dirs_exist_ok=True)\n",
    "    print('restored run dir from Drive ->', run_local)\n",
    "\n",
    "ck = os.path.join(run_local, 'weights', 'last.pt')\n",
    "if not os.path.exists(ck):\n",
    "    ck = os.path.join(run_drive, 'weights', 'last.pt')\n",
    "print('checkpoint:', ck)\n",
    "assert os.path.exists(ck), 'no last.pt - run Cell 12 first'\n",
    "\n",
    "meta = torch.load(ck, map_location='cpu', weights_only=False)\n",
    "ta = meta.get('train_args') or {}\n",
    "done, total = int(meta.get('epoch', -1)) + 1, int(ta.get('epochs', 0) or 0)\n",
    "resumable = meta.get('optimizer') is not None\n",
    "print('epoch %d/%d - optimizer %s' % (done, total, 'present' if resumable else 'STRIPPED (finished)'))\n",
    "if not resumable:\n",
    "    print('=> nothing to resume: this run is COMPLETE. Use Cell 15 to collect best.pt.')\n",
    "else:\n",
    "    with open(LOG_LOCAL, 'ab') as lf:\n",
    "        proc = subprocess.Popen([sys.executable, '-u', trainer, '--resume', ck],\n",
    "                                cwd='/content', stdout=lf, stderr=subprocess.STDOUT,\n",
    "                                start_new_session=True)\n",
    "    open(PIDFILE, 'w').write(str(proc.pid))\n",
    "    print('resumed detached, pid', proc.pid, '-> watch with Cell 13')\n",
])

C_COLLECT = code([
    "# Cell 15 - COLLECT the candidate onto Drive (md5 for the version registry)\n",
    "import hashlib, os, shutil\n",
    "from ultralytics import YOLO\n",
    "\n",
    "src = None\n",
    "for cand in (os.path.join(LOCAL_RUNS, NAME, 'weights', 'best.pt'),\n",
    "             os.path.join(RUNS, NAME, 'weights', 'best.pt'),\n",
    "             os.path.join(LOCAL_RUNS, NAME, 'weights', 'last.pt'),\n",
    "             os.path.join(RUNS, NAME, 'weights', 'last.pt')):\n",
    "    if os.path.exists(cand):\n",
    "        src = cand\n",
    "        break\n",
    "assert src, 'no checkpoint found - did Cell 12 run?'\n",
    "out = os.path.join(DRIVE_DIR, 'best_fireviewer_v6.pt')\n",
    "shutil.copy2(src, out)\n",
    "md5 = hashlib.md5(open(out, 'rb').read()).hexdigest()\n",
    "print('candidate ->', out)\n",
    "print('md5: %s | bytes: %d' % (md5, os.path.getsize(out)))\n",
    "fin = YOLO(out)\n",
    "assert list(fin.names.values()) == ['fire', 'other', 'smoke'], fin.names\n",
    "print('names OK ->', fin.names)\n",
])

C_NEXT = md([
    "## Next\n",
    "\n",
    "Pull `best_fireviewer_v6.pt` from `MyDrive/colab-data/v6-training/` into\n",
    "`model-training/fireviewer_v6_finetune/best_finetuned.pt`, then judge it **locally**\n",
    "against the full export (v4 baseline: mAP@50 0.392, fire image-recall 63.5 %,\n",
    "pyro-sdis smoke 2.4 %):\n",
    "\n",
    "```bash\n",
    "FV=model-training/datasets--fireviewer--fire-smoke-detection-corpus-v1\n",
    "sed 's#val: val/images#val: test/images#' \\\n",
    "    $FV/fireviewer_v1_yolo/data.yaml > $FV/fireviewer_v1_yolo/data_test.yaml\n",
    ".venv/bin/python dev_scripts/test_fire_model.py <ckpt> \\\n",
    "    $FV/fireviewer_v1_yolo/data_test.yaml --conf 0.5 --out <out>\n",
    "```\n",
    "\n",
    "Per-stage debug logs are on Drive at `MyDrive/colab-data/v6-training/logs/`\n",
    "(`05_download` … `13_status`).\n",
])


def _demagic(cells):
    """Glue any continuation line that begins with '%' back onto the previous line.

    A physical line starting with (optional whitespace +) '%' is ambiguous in a notebook
    cell: IPython's input transformer may read it as a line magic instead of Python's modulo
    operator, silently corrupting the cell. Wrapping an expression as

        print('value=%s'
              % (x,))

    is idiomatic Python, so rather than hand-wrapping every occurrence we force it onto one
    line here - that guarantees the invariant however the cell sources above are formatted.
    """
    for c in cells:
        if c["cell_type"] != "code":
            continue
        out = []
        for ln in "".join(c["source"]).split("\n"):
            if ln.lstrip().startswith("%") and out and out[-1].strip():
                out[-1] = out[-1].rstrip() + " " + ln.lstrip()
            else:
                out.append(ln)
        c["source"] = "\n".join(out)
    return cells


def _check_cross_cell_names(cells):
    """Refuse a notebook where a cell READS a name no EARLIER cell defines.

    Per-cell ``compile()`` only proves syntax, so it cannot catch this: `NAMES` was defined
    in the verify cell (Cell 9) but the balancer (Cell 8) used it, which blew up at runtime
    with NameError. This walks each cell's AST, accumulates the names every cell binds at
    module level (assignments, imports, def/class, args, except/with/for targets) and flags
    any read that no earlier cell bound - exactly the class of notebook-only bug that
    testing a single cell in isolation can never see.
    """
    import ast
    import builtins

    known = set(dir(builtins))
    problems = []
    for i, c in enumerate(cells, 1):
        if c["cell_type"] != "code":
            continue
        src = "".join(c["source"])
        try:
            tree = ast.parse(src)
        except SyntaxError:
            continue                                    # reported by the caller's compile pass
        stores, loads = set(), set()
        for node in ast.walk(tree):
            if isinstance(node, ast.Name):
                (stores if isinstance(node.ctx, ast.Store) else loads).add(node.id)
            elif isinstance(node, (ast.Import, ast.ImportFrom)):
                for a in node.names:
                    stores.add((a.asname or a.name).split(".")[0])
            elif isinstance(node, (ast.FunctionDef, ast.AsyncFunctionDef, ast.ClassDef)):
                stores.add(node.name)
            elif isinstance(node, ast.arg):
                stores.add(node.arg)
            elif isinstance(node, ast.ExceptHandler) and node.name:
                stores.add(node.name)
            elif isinstance(node, ast.Global):
                stores.update(node.names)
        missing = sorted(n for n in loads if n not in known and n not in stores)
        if missing:
            problems.append((i, missing))
        known |= stores
    if problems:
        raise SystemExit("refusing to write: a cell reads names no earlier cell defines "
                         "(cell, names): %r" % (problems[:3],))


def _check_no_magics(cells):
    """Refuse to write a notebook whose code cells could be mis-read as magics."""
    bad = [(i, ln.strip()[:60])
           for i, c in enumerate(cells, 1) if c["cell_type"] == "code"
           for ln in "".join(c["source"]).splitlines()
           if ln.lstrip().startswith("%")]
    if bad:
        raise SystemExit("refusing to write: '%%' at line start could be read as a magic: %r"
                         % bad[:3])


def build(out=DEFAULT_OUT):
    cells = _demagic([C_TITLE, C_SETUP, C_CONFIG, C_LOGGING, C_BUNDLE, C_DOWNLOAD, C_CONVERT,
                      C_DEDUP, C_BALANCE, C_VERIFY, C_NEGATIVES, C_TRAINER_CHECK, C_LAUNCH,
                      C_STATUS, C_WAIT, C_RESUME, C_COLLECT, C_NEXT])
    _check_no_magics(cells)
    _check_cross_cell_names(cells)
    nb = {
        "cells": cells,
        "metadata": {
            "colab": {"provenance": []},
            "kernelspec": {"name": "python3", "display_name": "Python 3"},
            "language_info": {"name": "python"},
        },
        "nbformat": 4,
        "nbformat_minor": 0,
    }
    os.makedirs(os.path.dirname(os.path.abspath(out)), exist_ok=True)
    with open(out, "w", encoding="utf-8") as fh:
        json.dump(nb, fh, indent=1, ensure_ascii=False)
    print(f"wrote {out} ({len(cells)} cells)")


def main():
    ap = argparse.ArgumentParser(description=__doc__,
                                 formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--out", default=DEFAULT_OUT,
                    help="notebook output path (default: %(default)s)")
    build(ap.parse_args().out)


if __name__ == "__main__":
    main()
