#!/usr/bin/env python3
"""build_colab_fireviewer_nb.py - generate the FireViewer v6 Colab notebook.

Prepares the dataset ON the Colab machine (the corpus is pulled from HuggingFace, so
nothing large is uploaded) and then trains in a way that survives losing the editor:

  * the upload bundle is read from Google Drive (`colab_upload.zip`, ~83 MB);
  * ALL run artifacts land on Drive - `<DRIVE>/runs/<name>/` holds `train.log`,
    `results.csv`, `args.yaml` and `weights/{last,best}.pt`;
  * training itself is launched DETACHED (`subprocess.Popen(start_new_session=True)` via
    dev_scripts/colab_train_v6.py), so closing VS Code / the tab / the kernel cannot stop
    it; the log is kept local for speed and mirrored to Drive every epoch;
  * dedicated STATUS and RESUME cells read `results.csv` / `last.pt` instead of relying on
    the notebook's stdout stream.

Cells: deps -> config -> Drive+bundle -> HF download -> convert -> dedup -> verify ->
negatives -> trainer check -> LAUNCH -> STATUS -> RESUME -> COLLECT.

Usage:
    python dev_scripts/build_colab_fireviewer_nb.py \
        --out model-training/datasets--fireviewer--fire-smoke-detection-corpus-v1/fireviewer-v6-bootstrap-colab.ipynb
"""
import argparse
import json
import os

DEFAULT_OUT = "notebooks/fireviewer-v6-bootstrap-colab.ipynb"


def md(source):
    return {"cell_type": "markdown", "metadata": {}, "source": source}


def code(source):
    return {"cell_type": "code", "execution_count": None, "metadata": {}, "outputs": [],
            "source": source}


C_TITLE = md([
    "# Fire model v6 — bootstrap + Drive-resilient fine-tune\n",
    "\n",
    "Builds the dataset **on the Colab machine** (the corpus is downloaded from HuggingFace —\n",
    "nothing large is uploaded) and fine-tunes **v4** (`models/fire/best.pt`).\n",
    "\n",
    "**Before you start:** put `colab_upload.zip` (built locally by\n",
    "`dev_scripts/pack_colab_upload.sh`, ~83 MB) in `MyDrive/colab-data/v6-training/`.\n",
    "\n",
    "**Everything durable lives on Drive** — `<DRIVE>/runs/<name>/` keeps `train.log`,\n",
    "`results.csv`, `args.yaml` and `weights/{last,best}.pt`, refreshed every epoch.\n",
    "Training is **detached**: closing VS Code or the tab does not stop it, and Cell 11\n",
    "re-attaches by reading `results.csv` / the log rather than the notebook's output stream.\n",
    "\n",
    "Plan: `plans/fire-model-v6-fireviewer-training.md`.\n",
])

C_SETUP = code([
    "# Cell 1 - deps + GPU\n",
    "!nvidia-smi\n",
    "!pip -q install --upgrade ultralytics pyarrow huggingface_hub\n",
    "import torch, ultralytics, pyarrow, huggingface_hub\n",
    "print('ultralytics', ultralytics.__version__, '| pyarrow', pyarrow.__version__)\n",
    "print('torch', torch.__version__, '| cuda', torch.cuda.is_available())\n",
    "assert torch.cuda.is_available(), 'pick a GPU runtime (Runtime -> Change runtime type)'\n",
])

C_CONFIG = code([
    "# Cell 2 - config\n",
    "DRIVE_DIR  = '/content/drive/MyDrive/colab-data/v6-training'\n",
    "DRIVE_ZIP  = DRIVE_DIR + '/colab_upload.zip'\n",
    "HF_REPO    = 'fireviewer/fire-smoke-detection-corpus-v1'\n",
    "CACHE      = '/content/fvcache'     # parquet download (temporary)\n",
    "YOLO_DS    = '/content/fv_yolo'     # converted YOLO dataset (train/ + val/)\n",
    "DUPS       = '/content/fv_dups'     # near-duplicates moved out of train\n",
    "UPLOAD     = '/content/upload'      # unpacked colab_upload.zip\n",
    "\n",
    "# --- where run artifacts live ---\n",
    "RUNS        = DRIVE_DIR + '/runs'   # every artifact is MIRRORED here every epoch\n",
    "LOCAL_RUNS  = '/content/runs'       # fast local project dir (Drive FUSE is slow)\n",
    "RUNS_MODE   = 'local_mirror'        # 'local_mirror' (default) | 'drive'\n",
    "LOG_LOCAL   = '/content/train.log'  # detached trainer stdout (mirrored to Drive)\n",
    "NAME        = 'v6-fireviewer'\n",
    "LOG_DRIVE   = RUNS + '/' + NAME + '/train.log'\n",
    "PIDFILE     = '/content/train.pid'\n",
    "\n",
    "# --- dataset build ---\n",
    "DEDUP_TRAIN   = True    # move near-duplicate TRAIN frames out (val is never touched)\n",
    "DEDUP_HAMMING = 8       # dHash distance; 6 conservative, 10 aggressive\n",
    "ADD_NEGATIVES = True    # inject our 841 domain negatives into TRAIN\n",
    "FREE_CACHE    = True    # delete the ~25 GB parquet cache before training\n",
    "\n",
    "# --- training ---\n",
    "EPOCHS   = 15     # ~33k images after dedup; patience stops early\n",
    "BATCH    = 16     # 32 on an L4, 64+ on an A100; 8 if a T4 OOMs\n",
    "IMGSZ    = 640    # matches production input\n",
    "FREEZE   = 10     # keep early backbone (less forgetting); 0 = full fine-tune\n",
    "LR0      = 0.001  # low LR for a pretrained fine-tune\n",
    "PATIENCE = 5      # early stop on the held-out val split\n",
    "SAVE_PERIOD = 1   # checkpoint every epoch -> survives a recycle\n",
])

C_BUNDLE = code([
    "# Cell 3 - mount Drive, unpack the (small) upload bundle\n",
    "import glob, os, shutil, zipfile\n",
    "from google.colab import drive\n",
    "drive.mount('/content/drive')\n",
    "\n",
    "os.makedirs(os.path.join(RUNS, NAME), exist_ok=True)   # the log needs a home on Drive\n",
    "if not os.path.isdir(UPLOAD) or not glob.glob(UPLOAD + '/*'):\n",
    "    assert os.path.exists(DRIVE_ZIP), ('missing ' + DRIVE_ZIP +\n",
    "        ' - build it with dev_scripts/pack_colab_upload.sh and upload it to ' + DRIVE_DIR)\n",
    "    os.makedirs(UPLOAD, exist_ok=True)\n",
    "    with zipfile.ZipFile(DRIVE_ZIP) as z:\n",
    "        z.extractall(UPLOAD)\n",
    "\n",
    "print('bundle contents:', sorted(os.listdir(UPLOAD)))\n",
    "assert os.path.exists(UPLOAD + '/model/best.pt'), 'best.pt missing from the bundle'\n",
    "assert os.path.exists(UPLOAD + '/scripts/colab_train_v6.py'), (\n",
    "    'colab_train_v6.py missing from the bundle - re-run dev_scripts/pack_colab_upload.sh')\n",
    "print('base      :', UPLOAD + '/model/best.pt')\n",
    "print('runs      :', RUNS)\n",
    "print('log       :', LOG_LOCAL, '-> mirrored to', LOG_DRIVE)\n",
])

C_DOWNLOAD = code([
    "# Cell 4 - download ONLY the parquet we train on (train + validation), idempotently\n",
    "from huggingface_hub import snapshot_download\n",
    "\n",
    "if glob.glob(CACHE + '/data/train/*.parquet'):\n",
    "    print('corpus already downloaded ->', CACHE)\n",
    "else:\n",
    "    snapshot_download(HF_REPO, repo_type='dataset', local_dir=CACHE,\n",
    "                      allow_patterns=['data/train/*', 'data/validation/*'])\n",
    "for sp in ('train', 'validation'):\n",
    "    print('  %-11s %d parquet shard(s)' % (sp, len(glob.glob('%s/data/%s/*.parquet' % (CACHE, sp)))))\n",
    "print('NOTE: the corpus test split is deliberately NOT downloaded - judge the model locally.')\n",
])

C_CONVERT = code([
    "# Cell 5 - convert parquet -> YOLO on the Colab disk (reuses the repo converter)\n",
    "import subprocess, sys\n",
    "\n",
    "conv = UPLOAD + '/scripts/prep_fireviewer_dataset.py'\n",
    "if os.path.isfile(YOLO_DS + '/data.yaml'):\n",
    "    print('already converted ->', YOLO_DS)\n",
    "else:\n",
    "    if os.path.isdir(YOLO_DS) and glob.glob(YOLO_DS + '/train/images/*'):\n",
    "        raise SystemExit('partial ' + YOLO_DS + ' - run `!rm -rf ' + YOLO_DS + '` then re-run')\n",
    "    subprocess.run([sys.executable, conv, '--corpus', CACHE, '--out', YOLO_DS,\n",
    "                    '--splits', 'train,validation'], check=True)\n",
    "print(open(YOLO_DS + '/data.yaml').read())\n",
])

C_DEDUP = code([
    "# Cell 6 - dedup TRAIN in place: move near-duplicate frames out (val untouched)\n",
    "# The corpus is already image-unique and cross-source deduped, but its video sources are\n",
    "# sampled per frame (pyro-sdis ~907 imgs/clip, boreal ~1420), so within-clip near-dups\n",
    "# dominate. Comparisons are bounded by the corpus' own split_group (one clip per group).\n",
    "import collections, csv, hashlib, os, shutil\n",
    "from PIL import Image\n",
    "\n",
    "if not DEDUP_TRAIN:\n",
    "    print('DEDUP_TRAIN=False -> skipped (val is never deduped regardless)')\n",
    "else:\n",
    "    os.makedirs(DUPS + '/images', exist_ok=True)\n",
    "    os.makedirs(DUPS + '/labels', exist_ok=True)\n",
    "\n",
    "    groups = collections.defaultdict(list)\n",
    "    with open(YOLO_DS + '/manifest.csv') as fh:\n",
    "        for r in csv.DictReader(fh):\n",
    "            if r['split'] == 'train':\n",
    "                groups[r['split_group']].append(r['stem'])\n",
    "\n",
    "    def _dhash(path):\n",
    "        im = Image.open(path).convert('L').resize((9, 8), Image.LANCZOS)\n",
    "        px = list(im.getdata())\n",
    "        bits = 0\n",
    "        for r in range(8):\n",
    "            for c in range(8):\n",
    "                bits = (bits << 1) | (1 if px[r * 9 + c] < px[r * 9 + c + 1] else 0)\n",
    "        return bits\n",
    "\n",
    "    kept_total = moved_total = 0\n",
    "    for gi, (grp, stems) in enumerate(groups.items(), 1):\n",
    "        kept, md5s = [], set()\n",
    "        for stem in stems:\n",
    "            img = YOLO_DS + '/train/images/' + stem + '.jpg'\n",
    "            if not os.path.exists(img):\n",
    "                continue\n",
    "            h = _dhash(img)\n",
    "            m = hashlib.md5(open(img, 'rb').read()).hexdigest()\n",
    "            dup = (m in md5s) or any(bin(kh ^ h).count('1') <= DEDUP_HAMMING for kh, _ in kept)\n",
    "            if dup:\n",
    "                shutil.move(img, DUPS + '/images/' + stem + '.jpg')\n",
    "                lp = YOLO_DS + '/train/labels/' + stem + '.txt'\n",
    "                if os.path.exists(lp):\n",
    "                    shutil.move(lp, DUPS + '/labels/' + stem + '.txt')\n",
    "                moved_total += 1\n",
    "            else:\n",
    "                md5s.add(m)\n",
    "                kept.append((h, stem))\n",
    "        kept_total += len(kept)\n",
    "        if gi % 200 == 0:\n",
    "            print('  groups %d/%d | kept %d | moved %d' % (gi, len(groups), kept_total, moved_total))\n",
    "    tot = kept_total + moved_total\n",
    "    msg = 'train kept %d/%d (%.1f%%) | near-dups moved: %d -> %s'\n",
    "    print(msg % (kept_total, tot, 100.0 * kept_total / tot if tot else 0.0, moved_total, DUPS))\n",
    "    print('val untouched:', len(os.listdir(YOLO_DS + '/val/images')), 'images')\n",
])

C_VERIFY = code([
    "# Cell 7 - verify the corpus structure after dedup (read-only, ~10-30 s)\n",
    "import collections, csv, os, random, shutil as _shutil\n",
    "\n",
    "NAMES = {0: 'fire', 1: 'other', 2: 'smoke'}\n",
    "EXT = ('.jpg', '.jpeg', '.png', '.bmp', '.webp')\n",
    "warn, fail = [], []\n",
    "for _sp in ('train', 'val'):                      # stale caches would mask changes\n",
    "    _c = os.path.join(YOLO_DS, _sp, 'labels.cache')\n",
    "    if os.path.exists(_c):\n",
    "        os.remove(_c)\n",
    "\n",
    "def split_stats(sp):\n",
    "    idir, ldir = os.path.join(YOLO_DS, sp, 'images'), os.path.join(YOLO_DS, sp, 'labels')\n",
    "    imgs = sorted(f for f in os.listdir(idir) if f.lower().endswith(EXT))\n",
    "    boxes, withcls = collections.Counter(), collections.Counter()\n",
    "    missing = bad = oor = 0\n",
    "    for f in imgs:\n",
    "        stem = os.path.splitext(f)[0]\n",
    "        lb = os.path.join(ldir, stem + '.txt')\n",
    "        if not os.path.isfile(lb):\n",
    "            missing += 1\n",
    "            continue\n",
    "        present, n = set(), 0\n",
    "        for row in open(lb):\n",
    "            parts = row.split()\n",
    "            if not parts:\n",
    "                continue\n",
    "            if len(parts) != 5:\n",
    "                bad += 1\n",
    "                continue\n",
    "            try:\n",
    "                c = int(float(parts[0]))\n",
    "                vals = [float(v) for v in parts[1:]]\n",
    "            except ValueError:\n",
    "                bad += 1\n",
    "                continue\n",
    "            if c not in NAMES:\n",
    "                bad += 1\n",
    "                continue\n",
    "            if any(v < 0.0 or v > 1.0 for v in vals):\n",
    "                oor += 1\n",
    "            boxes[NAMES[c]] += 1\n",
    "            present.add(NAMES[c])\n",
    "            n += 1\n",
    "        for k in present:                         # count each class ONCE per image\n",
    "            withcls[k] += 1\n",
    "        if n == 0:\n",
    "            withcls['background'] += 1\n",
    "    labels = [f for f in os.listdir(ldir) if f.endswith('.txt')]\n",
    "    stems = {os.path.splitext(f)[0] for f in imgs}\n",
    "    orphan = sum(1 for f in labels if os.path.splitext(f)[0] not in stems)\n",
    "    return dict(n=len(imgs), labels=len(labels), boxes=boxes, withcls=withcls,\n",
    "                missing=missing, orphan=orphan, bad=bad, oor=oor)\n",
    "\n",
    "print('=' * 74)\n",
    "print('Corpus AFTER dedup ->', YOLO_DS)\n",
    "print('=' * 74)\n",
    "st = {}\n",
    "for sp in ('train', 'val'):\n",
    "    s = st[sp] = split_stats(sp)\n",
    "    print()\n",
    "    print('[%s] images=%d  label files=%d' % (sp, s['n'], s['labels']))\n",
    "    print('   boxes     : ' + (', '.join(k + '=' + str(v) for k, v in sorted(s['boxes'].items())) or '-'))\n",
    "    print('   images w/ : ' + (', '.join(k + '=' + str(v) for k, v in sorted(s['withcls'].items())) or '-'))\n",
    "    msg = '   integrity : missing_label=%d orphan_labels=%d malformed_rows=%d coords_out_of_range=%d'\n",
    "    print(msg % (s['missing'], s['orphan'], s['bad'], s['oor']))\n",
    "    if s['missing'] or s['orphan'] or s['bad'] or s['oor']:\n",
    "        fail.append(sp + ': integrity problems')\n",
    "    for cls in ('fire', 'smoke'):\n",
    "        if s['boxes'].get(cls, 0) == 0:\n",
    "            (fail if sp == 'val' else warn).append(sp + ': no ' + cls + ' boxes')\n",
    "\n",
    "tr = st['train']\n",
    "if tr['n'] and tr['withcls'].get('background', 0) / tr['n'] > 0.80:\n",
    "    warn.append('train background share %.1f%%' % (100.0 * tr['withcls']['background'] / tr['n']))\n",
    "\n",
    "mf = os.path.join(YOLO_DS, 'manifest.csv')\n",
    "if os.path.isfile(mf):\n",
    "    have = {os.path.splitext(f)[0] for f in os.listdir(YOLO_DS + '/train/images')}\n",
    "    before, after = collections.Counter(), collections.Counter()\n",
    "    gb, ga = collections.Counter(), collections.Counter()\n",
    "    with open(mf) as fh:\n",
    "        for r in csv.DictReader(fh):\n",
    "            if r['split'] != 'train':\n",
    "                continue\n",
    "            gb[r['split_group']] += 1\n",
    "            before[r['source_name']] += 1\n",
    "            if r['stem'] in have:\n",
    "                after[r['source_name']] += 1\n",
    "                ga[r['split_group']] += 1\n",
    "    print()\n",
    "    print('per-source survival (train):')\n",
    "    print('   %-12s %8s %8s %9s %8s' % ('source', 'before', 'after', 'removed', 'keep'))\n",
    "    tb = ta = 0\n",
    "    for src in sorted(before):\n",
    "        b, a = before[src], after[src]\n",
    "        tb += b\n",
    "        ta += a\n",
    "        print('   %-12s %8d %8d %9d %7.1f%%' % (src, b, a, b - a, 100.0 * a / b if b else 0.0))\n",
    "    print('   %-12s %8d %8d %9d %7.1f%%' % ('TOTAL', tb, ta, tb - ta, 100.0 * ta / tb if tb else 0.0))\n",
    "    live = [g for g, n in ga.items() if n]\n",
    "    print()\n",
    "    print('clips still present : %d / %d' % (len(live), len(gb)))\n",
    "    _m = 'largest live clip   : %d frames (was %d)'\n",
    "    print(_m % (max(ga.values()) if ga else 0, max(gb.values()) if gb else 0))\n",
    "    if ga and gb and max(ga.values()) > 0.5 * max(gb.values()):\n",
    "        _m2 = 'largest live clip is %.0f%% of the original - dedup may not have bitten'\n",
    "        warn.append(_m2 % (100.0 * max(ga.values()) / max(gb.values())))\n",
    "else:\n",
    "    warn.append('manifest.csv missing - per-source survival not computed')\n",
    "\n",
    "idir = os.path.join(YOLO_DS, 'train', 'images')\n",
    "files = sorted(os.listdir(idir))\n",
    "random.seed(0)\n",
    "sample = random.sample(files, min(800, len(files)))\n",
    "hs = [globals()['_dhash'](os.path.join(idir, f)) if '_dhash' in globals()\n",
    "      else 0 for f in sample]\n",
    "near = 0\n",
    "if '_dhash' in globals():\n",
    "    for i in range(len(hs)):\n",
    "        for j in range(i + 1, len(hs)):\n",
    "            if bin(hs[i] ^ hs[j]).count('1') <= DEDUP_HAMMING:\n",
    "                near += 1\n",
    "    pairs = len(hs) * (len(hs) - 1) // 2\n",
    "    print()\n",
    "    msg = 'residual near-dups: %d pair(s) <=%d among %d random train images (%.3f%% of %d pairs)'\n",
    "    print(msg % (near, DEDUP_HAMMING, len(hs), 100.0 * near / pairs if pairs else 0.0, pairs))\n",
    "    if pairs and near / pairs > 0.005:\n",
    "        warn.append('%d residual near-dup pair(s) (%.3f%%)' % (near, 100.0 * near / pairs))\n",
    "else:\n",
    "    print('\\n(residual check skipped: run Cell 6 first - _dhash not defined)')\n",
    "\n",
    "print()\n",
    "print(open(os.path.join(YOLO_DS, 'data.yaml')).read().strip())\n",
    "dups = len(os.listdir(DUPS + '/images')) if os.path.isdir(DUPS + '/images') else 0\n",
    "print()\n",
    "print('dups moved out : %d images in %s' % (dups, DUPS))\n",
    "print('/content free  : %.1f GB' % (_shutil.disk_usage('/content').free / 1e9))\n",
    "print()\n",
    "print('RESULT: ' + ('FAIL - ' + '; '.join(fail) if fail else\n",
    "                    ('WARN - ' + '; '.join(warn) if warn else 'PASS')))\n",
])

C_NEGATIVES = code([
    "# Cell 8 - add our domain negatives to TRAIN (empty label = background), free the cache\n",
    "if ADD_NEGATIVES:\n",
    "    neg = UPLOAD + '/negatives'\n",
    "    ti, tl = YOLO_DS + '/train/images', YOLO_DS + '/train/labels'\n",
    "    added = 0\n",
    "    for f in sorted(glob.glob(neg + '/*')):\n",
    "        if os.path.splitext(f)[1].lower() not in ('.jpg', '.jpeg', '.png'):\n",
    "            continue\n",
    "        base = os.path.basename(f)\n",
    "        if not os.path.exists(os.path.join(ti, base)):\n",
    "            shutil.copy2(f, os.path.join(ti, base))\n",
    "        open(os.path.join(tl, os.path.splitext(base)[0] + '.txt'), 'w').close()\n",
    "        added += 1\n",
    "    print('negatives added to TRAIN:', added)\n",
    "else:\n",
    "    print('ADD_NEGATIVES=False -> corpus-only run')\n",
    "\n",
    "print('audit set (our real fires, HELD OUT):', UPLOAD + '/audit',\n",
    "      len(glob.glob(UPLOAD + '/audit/*')), 'imgs')\n",
    "print('train images now:', len(os.listdir(YOLO_DS + '/train/images')))\n",
    "\n",
    "if FREE_CACHE:\n",
    "    shutil.rmtree(CACHE, ignore_errors=True)\n",
    "    print('parquet cache removed ->', CACHE)\n",
    "else:\n",
    "    print('FREE_CACHE=False -> keeping', CACHE, '(re-used by a second run)')\n",
    "print('/content free: %.1f GB' % (shutil.disk_usage('/content').free / 1e9))\n",
])

C_TRAINER_CHECK = code([
    "# Cell 9 - sanity-check the detached trainer that ships in the bundle\n",
    "import subprocess, sys\n",
    "trainer = UPLOAD + '/scripts/colab_train_v6.py'\n",
    "print(subprocess.run([sys.executable, trainer, '--help'], capture_output=True, text=True).stdout[:900])\n",
])

C_LAUNCH = code([
    "# Cell 10 - LAUNCH training DETACHED (closing VS Code will NOT stop it)\n",
    "import os, subprocess, sys\n",
    "\n",
    "# refuse to start a second trainer on the same GPU (two would OOM)\n",
    "if os.path.exists(PIDFILE):\n",
    "    _old = int(open(PIDFILE).read().strip() or 0)\n",
    "    try:\n",
    "        os.kill(_old, 0)\n",
    "        raise SystemExit('a trainer is already running (pid %d). Use Cell 11 to watch it, '\n",
    "                         'or kill it first: !kill -9 %d' % (_old, _old))\n",
    "    except OSError:\n",
    "        pass\n",
    "\n",
    "os.makedirs(os.path.join(RUNS, NAME), exist_ok=True)\n",
    "args = [sys.executable, '-u', trainer,\n",
    "        '--data', YOLO_DS + '/data.yaml', '--base', UPLOAD + '/model/best.pt',\n",
    "        '--runs', RUNS, '--name', NAME, '--mode', RUNS_MODE, '--local', LOCAL_RUNS,\n",
    "        '--log', LOG_LOCAL,\n",
    "        '--epochs', str(EPOCHS), '--batch', str(BATCH), '--imgsz', str(IMGSZ),\n",
    "        '--freeze', str(FREEZE), '--lr0', str(LR0), '--patience', str(PATIENCE),\n",
    "        '--save-period', str(SAVE_PERIOD)]\n",
    "with open(LOG_LOCAL, 'ab') as lf:\n",
    "    proc = subprocess.Popen(args, cwd='/content', stdout=lf,\n",
    "                            stderr=subprocess.STDOUT, start_new_session=True)\n",
    "open(PIDFILE, 'w').write(str(proc.pid))\n",
    "print('launched pid %d (own session -> survives losing the editor/kernel)' % proc.pid)\n",
    "print('local log :', LOG_LOCAL)\n",
    "print('Drive log :', LOG_DRIVE, '(mirrored every epoch)')\n",
    "print('Drive run :', os.path.join(RUNS, NAME))\n",
    "print('next      : run Cell 11 to watch progress')\n",
])

C_STATUS = code([
    "# Cell 11 - STATUS: re-attach to the detached run (no stdout stream needed)\n",
    "import os, subprocess, time\n",
    "\n",
    "pid = int(open(PIDFILE).read().strip() or 0) if os.path.exists(PIDFILE) else None\n",
    "alive = False\n",
    "if pid:\n",
    "    try:\n",
    "        os.kill(pid, 0)\n",
    "        alive = True\n",
    "    except OSError:\n",
    "        alive = False\n",
    "print('trainer pid %s -> %s' % (pid, 'RUNNING' if alive else 'not running'))\n",
    "\n",
    "def describe(label, d):\n",
    "    print('\\n[%s] %s' % (label, d))\n",
    "    if not os.path.isdir(d):\n",
    "        print('   (missing)')\n",
    "        return\n",
    "    csvp = os.path.join(d, 'results.csv')\n",
    "    if os.path.exists(csvp):\n",
    "        rows = [r for r in open(csvp).read().splitlines() if r.strip()]\n",
    "        print('   results.csv  epochs=%d  age=%ds' % (max(0, len(rows) - 1),\n",
    "                                                     int(time.time() - os.path.getmtime(csvp))))\n",
    "        if len(rows) > 1:\n",
    "            print('   last row    :', rows[-1][:140])\n",
    "    w = os.path.join(d, 'weights')\n",
    "    if os.path.isdir(w):\n",
    "        for f in sorted(os.listdir(w)):\n",
    "            p = os.path.join(w, f)\n",
    "            print('   %-9s %7.1f MB  age=%ds' % (f, os.path.getsize(p) / 1e6,\n",
    "                                                 int(time.time() - os.path.getmtime(p))))\n",
    "\n",
    "describe('local', os.path.join(LOCAL_RUNS, NAME))\n",
    "describe('Drive', os.path.join(RUNS, NAME))\n",
    "\n",
    "print('\\n-- local log tail --')\n",
    "if os.path.exists(LOG_LOCAL):\n",
    "    lines = open(LOG_LOCAL, errors='replace').read().splitlines()\n",
    "    print('\\n'.join(lines[-15:]))\n",
    "else:\n",
    "    print('(no log yet)')\n",
    "\n",
    "print('\\n-- GPU --')\n",
    "print(subprocess.run(['nvidia-smi', '--query-gpu=utilization.gpu,memory.used',\n",
    "                      '--format=csv,noheader'], capture_output=True, text=True).stdout.strip() or '(n/a)')\n",
    "print(subprocess.run(['nvidia-smi', '--query-compute-apps=pid,used_memory',\n",
    "                      '--format=csv,noheader'], capture_output=True, text=True).stdout.strip() or '(no GPU process)')\n",
])

C_RESUME = code([
    "# Cell 12 - RESUME an interrupted run (detached too). Refuses if the run FINISHED.\n",
    "# Ultralytics strips the optimizer from a completed last.pt, so resuming one would\n",
    "# silently start a brand-new run on the default dataset - hence the inspection.\n",
    "import os, shutil, subprocess, sys, torch\n",
    "\n",
    "run_local, run_drive = os.path.join(LOCAL_RUNS, NAME), os.path.join(RUNS, NAME)\n",
    "if not os.path.isdir(run_local) and os.path.isdir(run_drive):\n",
    "    # fresh VM: restore the run dir locally so the per-epoch Drive mirror keeps working\n",
    "    shutil.copytree(run_drive, run_local, dirs_exist_ok=True)\n",
    "    print('restored run dir from Drive ->', run_local)\n",
    "\n",
    "ck = os.path.join(run_local, 'weights', 'last.pt')\n",
    "if not os.path.exists(ck):\n",
    "    ck = os.path.join(run_drive, 'weights', 'last.pt')\n",
    "print('checkpoint:', ck)\n",
    "assert os.path.exists(ck), 'no last.pt - run Cell 10 first'\n",
    "\n",
    "meta = torch.load(ck, map_location='cpu', weights_only=False)\n",
    "ta = meta.get('train_args') or {}\n",
    "done, total = int(meta.get('epoch', -1)) + 1, int(ta.get('epochs', 0) or 0)\n",
    "resumable = meta.get('optimizer') is not None\n",
    "print('epoch %d/%d - optimizer %s' % (done, total, 'present' if resumable else 'STRIPPED (finished)'))\n",
    "if not resumable:\n",
    "    print('=> nothing to resume: this run is COMPLETE. Use Cell 13 to collect best.pt.')\n",
    "else:\n",
    "    with open(LOG_LOCAL, 'ab') as lf:\n",
    "        proc = subprocess.Popen([sys.executable, '-u', trainer, '--resume', ck],\n",
    "                                cwd='/content', stdout=lf, stderr=subprocess.STDOUT,\n",
    "                                start_new_session=True)\n",
    "    open(PIDFILE, 'w').write(str(proc.pid))\n",
    "    print('resumed detached, pid', proc.pid, '-> watch with Cell 11')\n",
])

C_COLLECT = code([
    "# Cell 13 - COLLECT the candidate onto Drive (md5 for the version registry)\n",
    "import hashlib, os, shutil\n",
    "from ultralytics import YOLO\n",
    "\n",
    "src = None\n",
    "for cand in (os.path.join(LOCAL_RUNS, NAME, 'weights', 'best.pt'),\n",
    "             os.path.join(RUNS, NAME, 'weights', 'best.pt'),\n",
    "             os.path.join(LOCAL_RUNS, NAME, 'weights', 'last.pt'),\n",
    "             os.path.join(RUNS, NAME, 'weights', 'last.pt')):\n",
    "    if os.path.exists(cand):\n",
    "        src = cand\n",
    "        break\n",
    "assert src, 'no checkpoint found - did Cell 10 run?'\n",
    "out = os.path.join(DRIVE_DIR, 'best_fireviewer_v6.pt')\n",
    "shutil.copy2(src, out)\n",
    "md5 = hashlib.md5(open(out, 'rb').read()).hexdigest()\n",
    "print('candidate ->', out)\n",
    "print('md5: %s | bytes: %d' % (md5, os.path.getsize(out)))\n",
    "fin = YOLO(out)\n",
    "assert list(fin.names.values()) == ['fire', 'other', 'smoke'], fin.names\n",
    "print('names OK ->', fin.names)\n",
])

C_NEXT = md([
    "## Next\n",
    "\n",
    "Pull `best_fireviewer_v6.pt` from `MyDrive/colab-data/v6-training/` into\n",
    "`model-training/fireviewer_v6_finetune/best_finetuned.pt`, then judge it **locally**\n",
    "against the full export (v4 baseline: mAP@50 0.392, fire image-recall 63.5 %,\n",
    "pyro-sdis smoke 2.4 %):\n",
    "\n",
    "```bash\n",
    "FV=model-training/datasets--fireviewer--fire-smoke-detection-corpus-v1\n",
    "sed 's#val: val/images#val: test/images#' \\\n",
    "    $FV/fireviewer_v1_yolo/data.yaml > $FV/fireviewer_v1_yolo/data_test.yaml\n",
    ".venv/bin/python dev_scripts/test_fire_model.py <ckpt> \\\n",
    "    $FV/fireviewer_v1_yolo/data_test.yaml --conf 0.5 --out <out>\n",
    "```\n",
    "\n",
    "Then run the recall guard and only promote if fire recall holds.\n",
])


def build(out=DEFAULT_OUT):
    cells = [C_TITLE, C_SETUP, C_CONFIG, C_BUNDLE, C_DOWNLOAD, C_CONVERT, C_DEDUP,
             C_VERIFY, C_NEGATIVES, C_TRAINER_CHECK, C_LAUNCH, C_STATUS, C_RESUME,
             C_COLLECT, C_NEXT]
    nb = {
        "cells": cells,
        "metadata": {
            "colab": {"provenance": []},
            "kernelspec": {"name": "python3", "display_name": "Python 3"},
            "language_info": {"name": "python"},
        },
        "nbformat": 4,
        "nbformat_minor": 0,
    }
    os.makedirs(os.path.dirname(os.path.abspath(out)), exist_ok=True)
    with open(out, "w", encoding="utf-8") as fh:
        json.dump(nb, fh, indent=1, ensure_ascii=False)
    print(f"wrote {out} ({len(cells)} cells)")


def main():
    ap = argparse.ArgumentParser(description=__doc__,
                                 formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--out", default=DEFAULT_OUT,
                    help="notebook output path (default: %(default)s)")
    build(ap.parse_args().out)


if __name__ == "__main__":
    main()
