#!/usr/bin/env bash
# pack_fire_scratch_colab.sh - build the SMALL Colab upload bundle for the scratch fire-model run.
#
# The EXTERNAL training sets are NOT uploaded: Colab downloads them straight from their
# sources (the FireViewer HF corpus, Roboflow/zip URLs, ...) - that is the whole point of
# prep_fire_scratch_dataset.py. Only the things that exist nowhere else go in this bundle:
#
#   scripts/prep_fire_scratch_dataset.py   download + merge external sources -> raw YOLO tree
#   scripts/prep_fireviewer_dataset.py     parquet->YOLO converter (dependency of the above)
#   scripts/dedup_fire_scratch.py          the dedup passes + lightweight fingerprint index
#   scripts/colab_train_scratch.py         the detached, Drive-resilient SCRATCH trainer
#   cctv_emergency/                        Simuletic CCTV Emergency (240) - merged into TRAIN
#   domain_test/                           our own CCTV TRUE fires (HELD OUT - never trained)
#   negatives/                             our domain hard negatives -> train as background
#
# Abonia fire-8 is NOT bundled: the notebook fetches it from its GitHub source
# (Abonia1/YOLOv8-Fire-and-Smoke-Detection, datasets/fire-8) via a sparse clone.
#
# Usage:
#   ./dev_scripts/pack_fire_scratch_colab.sh [output.zip]
# Default output: model-training/fire_scratch_colab/colab_upload.zip
set -euo pipefail

ROOT="$(cd "$(dirname "$0")/.." && pwd)"
cd "$ROOT"
MT="model-training"
OUT="${1:-$MT/fire_scratch_colab/colab_upload.zip}"
case "$OUT" in /*) ;; *) OUT="$ROOT/$OUT" ;; esac

WORK="$(mktemp -d)"
trap 'rm -rf "$WORK"' EXIT
mkdir -p "$WORK/negatives" "$WORK/domain_test" "$WORK/scripts"
mkdir -p "$WORK/cctv_emergency"

# Copy images only - RECURSIVELY (some sets nest under images/camNN/) - and never the
# annotated (overlay-burned) variants, which would teach the model the drawn boxes.
# A basename collision across subdirs is disambiguated with the parent dir name.
copy_imgs() {
  local src="$1" dst="$2" f b p
  [ -d "$src" ] || { echo "  (skip, absent) $src"; return 0; }
  while IFS= read -r -d '' f; do
    b="$(basename "$f")"
    if [ -e "$dst/$b" ]; then
      p="$(basename "$(dirname "$f")")"
      b="${p}__${b}"
    fi
    cp "$f" "$dst/$b"
  done < <(find "$src" -type f \
                \( -iname '*.jpg' -o -iname '*.jpeg' -o -iname '*.png' \) \
                ! -iname '*annotated*' -print0)
}

echo "collecting domain negatives -> $WORK/negatives"
copy_imgs "$MT/false-negatives/default-other"                          "$WORK/negatives"
copy_imgs "$MT/false-negatives/climate"                                "$WORK/negatives"
copy_imgs "$MT/false-negatives/dogs"                                   "$WORK/negatives"
copy_imgs "$MT/false-negatives/places"                                 "$WORK/negatives"
copy_imgs "$MT/our-cctv/dog-fp-alerts"                                 "$WORK/negatives"
copy_imgs "$MT/our-camera-clips/fire_events_over_0_5_false_positives"  "$WORK/negatives"

echo "collecting our-domain CCTV true fires (held-out test) -> $WORK/domain_test"
copy_imgs "$MT/our-camera-clips/fire_events_over_0_5"                  "$WORK/domain_test"

echo "bundling CCTV Emergency (flat images+labels YOLO layout)"
if [ -d "$MT/4_CCTV_Emergency" ]; then
  cp -r "$MT/4_CCTV_Emergency/." "$WORK/cctv_emergency/"
else
  echo "  (skip, absent) $MT/4_CCTV_Emergency"
fi

echo "bundling scripts"
cp dev_scripts/prep_fire_scratch_dataset.py \
   dev_scripts/prep_fireviewer_dataset.py \
   dev_scripts/dedup_fire_scratch.py \
   dev_scripts/colab_train_scratch.py "$WORK/scripts/"

printf 'Fire scratch Colab upload bundle\ncreated (UTC): %s\ngit: %s\n' \
  "$(date -u +%Y-%m-%dT%H:%M:%SZ)" "$(git rev-parse --short HEAD 2>/dev/null || echo n/a)" \
  > "$WORK/BUNDLE.txt"

mkdir -p "$(dirname "$OUT")"
rm -f "$OUT"
( cd "$WORK" && zip -qr "$OUT" . )

n_neg=$(find "$WORK/negatives" -type f | wc -l)
n_dom=$(find "$WORK/domain_test" -type f | wc -l)
echo
echo "negatives   : $n_neg images ($(du -sh "$WORK/negatives" | cut -f1))"
echo "domain_test : $n_dom images ($(du -sh "$WORK/domain_test" | cut -f1))"
echo "bundle      -> $OUT  ($(du -h "$OUT" | cut -f1))"
echo
echo "Upload that one file to Google Drive:  MyDrive/mazr3a-fire-scratch/colab_upload.zip"
echo "then run the Colab notebook generated by dev_scripts/build_fire_scratch_colab_nb.py"
echo "(it reads colab_upload.zip from that Drive folder)."
