#!/usr/bin/env bash
# pack_colab_upload.sh - build the SMALL Colab upload bundle for the fire-model v6 run.
#
# The FireViewer corpus is NOT uploaded: Colab downloads it straight from HuggingFace
# (`fireviewer/fire-smoke-detection-corpus-v1`) and prepares the images on the VM. Only
# the things that exist nowhere else go in this bundle, so a narrow uplink is fine
# (~90 MB total, vs ~31 GB for the corpus / its YOLO export):
#
#   negatives/                     our domain hard negatives -> added to TRAIN as background
#                                  (empty labels): false-negatives/{default-other,climate,
#                                  dogs,places}, our-cctv/dog-fp-alerts, and the curated
#                                  cam dog/FP frames (fire_events_over_0_5_false_positives).
#                                  `*annotated*` files are skipped - they carry drawn overlays.
#   audit/                         our-cctv TRUE fires (fire_events_over_0_5) - HELD OUT, used
#                                  to check that our own real fires are still detected.
#   model/                         models/fire/best.pt (v4 base) + labelmap.txt
#   scripts/prep_fireviewer_dataset.py   the parquet->YOLO converter, run inside Colab
#
# Usage:
#   ./dev_scripts/pack_colab_upload.sh [output.zip]
# Default output: model-training/datasets--fireviewer--fire-smoke-detection-corpus-v1/colab_upload.zip
set -euo pipefail

ROOT="$(cd "$(dirname "$0")/.." && pwd)"
cd "$ROOT"
MT="model-training"
OUT="${1:-$MT/datasets--fireviewer--fire-smoke-detection-corpus-v1/colab_upload.zip}"
case "$OUT" in /*) ;; *) OUT="$ROOT/$OUT" ;; esac

WORK="$(mktemp -d)"
trap 'rm -rf "$WORK"' EXIT
mkdir -p "$WORK/negatives" "$WORK/audit" "$WORK/model" "$WORK/scripts"

# Copy images only - RECURSIVELY (some sets nest under images/camNN/) - and never the
# annotated (overlay-burned) variants, which would teach the model the drawn boxes.
# A basename collision across subdirs is disambiguated with the parent dir name.
copy_imgs() {
  local src="$1" dst="$2" f b p
  [ -d "$src" ] || { echo "  (skip, absent) $src"; return 0; }
  while IFS= read -r -d '' f; do
    b="$(basename "$f")"
    if [ -e "$dst/$b" ]; then
      p="$(basename "$(dirname "$f")")"
      b="${p}__${b}"
    fi
    cp "$f" "$dst/$b"
  done < <(find "$src" -type f \
                \( -iname '*.jpg' -o -iname '*.jpeg' -o -iname '*.png' \) \
                ! -iname '*annotated*' -print0)
}

echo "collecting negatives -> $WORK/negatives"
copy_imgs "$MT/false-negatives/default-other"                          "$WORK/negatives"
copy_imgs "$MT/false-negatives/climate"                                "$WORK/negatives"
copy_imgs "$MT/false-negatives/dogs"                                   "$WORK/negatives"
copy_imgs "$MT/false-negatives/places"                                 "$WORK/negatives"
copy_imgs "$MT/our-cctv/dog-fp-alerts"                                 "$WORK/negatives"
copy_imgs "$MT/our-camera-clips/fire_events_over_0_5_false_positives"  "$WORK/negatives"

echo "collecting our-domain fire audit set -> $WORK/audit"
copy_imgs "$MT/our-camera-clips/fire_events_over_0_5"                  "$WORK/audit"

echo "bundling base checkpoint + converter"
cp models/fire/best.pt models/fire/labelmap.txt "$WORK/model/"
cp dev_scripts/prep_fireviewer_dataset.py "$WORK/scripts/"

printf 'FireViewer v6 Colab upload bundle\ncreated (UTC): %s\ngit: %s\n' \
  "$(date -u +%Y-%m-%dT%H:%M:%SZ)" "$(git rev-parse --short HEAD 2>/dev/null || echo n/a)" \
  > "$WORK/BUNDLE.txt"

rm -f "$OUT"
( cd "$WORK" && zip -qr "$OUT" . )

n_neg=$(find "$WORK/negatives" -type f | wc -l)
n_aud=$(find "$WORK/audit" -type f | wc -l)
echo
echo "negatives : $n_neg images ($(du -sh "$WORK/negatives" | cut -f1))"
echo "audit     : $n_aud images ($(du -sh "$WORK/audit" | cut -f1))"
echo "bundle    -> $OUT  ($(du -h "$OUT" | cut -f1))"
echo
echo "Upload that one file to Google Drive (e.g. MyDrive/mazr3a/) and run the Colab"
echo "notebook generated by dev_scripts/build_colab_fireviewer_nb.py."
